// effect-http — Effect 4 HTTP client
// Generated by fizzyx. Only what you use ships.

import { Effect } from "effect";
import * as FetchHttpClient from "effect/unstable/http/FetchHttpClient";
import * as HttpBody from "effect/unstable/http/HttpBody";
import * as HttpClient from "effect/unstable/http/HttpClient";
import * as HttpClientError from "effect/unstable/http/HttpClientError";
import * as HttpClientRequest from "effect/unstable/http/HttpClientRequest";
import * as HttpClientResponse from "effect/unstable/http/HttpClientResponse";

export type EffectHttpClientError = HttpClientError.HttpClientError | HttpBody.HttpBodyError;

export interface EffectClientConfig {
	/** API base URL (prepended to relative paths). */
	baseUrl?: string;
	/** Default headers sent with every request. */
	headers?: Record<string, string>;
	/**
	 * Transform the raw response body before returning.
	 * Default unwraps `{ code, data }` envelope → `data`.
	 * Set to `(raw) => raw` to disable unwrapping.
	 */
	responseExtractor?: (raw: unknown) => unknown;
}

export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS";

export const FetchLayer = FetchHttpClient.layer;

let _config: EffectClientConfig = {};
let _token: string | null = null;
let _defaultHeaders: Record<string, string> = {};

/** Configure the client. Call once at app startup. */
export function configure(config: EffectClientConfig): void {
	_config = { ..._config, ...config };
}

/** Set auth token. Pass `null` to clear. */
export function setToken(token: string | null): void {
	_token = token;
}

/** Set default headers sent with every request. Merge with existing defaults. */
export function setHeaders(headers: Record<string, string>): void {
	_defaultHeaders = { ..._defaultHeaders, ...headers };
}

function defaultExtractor(raw: unknown): unknown {
	if (
		raw !== null &&
		typeof raw === "object" &&
		"code" in (raw as Record<string, unknown>) &&
		"data" in (raw as Record<string, unknown>)
	) {
		return (raw as Record<string, unknown>).data;
	}
	return raw;
}

function buildUrl(url: string, query?: Record<string, unknown>): string {
	let finalUrl = url.startsWith("http") ? url : (_config.baseUrl ?? "") + url;
	if (query) {
		const params = new URLSearchParams();
		for (const [key, val] of Object.entries(query)) {
			if (val === undefined) continue;
			if (Array.isArray(val)) {
				for (const item of val) {
					if (item !== undefined) params.append(key, String(item));
				}
			} else {
				params.set(key, String(val));
			}
		}
		const qs = params.toString();
		if (qs) finalUrl += (finalUrl.includes("?") ? "&" : "?") + qs;
	}
	return finalUrl;
}

function readResponse(
	response: HttpClientResponse.HttpClientResponse,
): Effect.Effect<unknown, HttpClientError.HttpClientError> {
	const contentType = response.headers["content-type"] ?? "";
	return contentType.includes("application/json") ? response.json : response.text;
}

/**
 * Typed Effect request using Effect 4's HttpClient service.
 *
 * Provide a transport at the program boundary, for example:
 * `program.pipe(Effect.provide(FetchLayer))`
 */
export function execute<T, B = unknown>(
	method: HttpMethod,
	url: string,
	options?: { query?: Record<string, unknown>; body?: B; headers?: Record<string, string> },
): Effect.Effect<T, EffectHttpClientError, HttpClient.HttpClient> {
	const httpRequest = Effect.sync(() => {
		const finalUrl = buildUrl(url, options?.query);
		const headers: Record<string, string> = {
			..._config.headers,
			..._defaultHeaders,
			...options?.headers,
		};
		if (_token) headers["Authorization"] = `Bearer ${_token}`;

		return HttpClientRequest.make(method)(finalUrl, {
			headers,
			acceptJson: true,
		});
	}).pipe(
		Effect.flatMap((baseRequest) =>
			options?.body === undefined
				? Effect.succeed(baseRequest)
				: HttpClientRequest.bodyJson(options.body)(baseRequest),
		),
	);

	return httpRequest.pipe(
		Effect.flatMap((request) => HttpClient.execute(request)),
		Effect.flatMap(HttpClientResponse.filterStatusOk),
		Effect.flatMap(readResponse),
		Effect.map((raw) => {
			const extractor = _config.responseExtractor || defaultExtractor;
			return extractor(raw) as T;
		}),
	);
}
