// Generated by fizzyx. Do not edit.

import { Effect } from "effect";
import * as HttpClient from "effect/unstable/http/HttpClient";
import { execute } from "./effect-http";
import type { EffectHttpClientError } from "./effect-http";
export type { EffectClientConfig, EffectHttpClientError, HttpMethod } from "./effect-http";
export { FetchLayer, configure, setToken, setHeaders } from "./effect-http";
import type {
	AssignCardRequestContent,
	BulkReadNotificationsRequestContent,
	CompleteJoinRequestContent,
	CompleteSignupRequestContent,
	CreateAccessTokenRequestContent,
	CreateAccessTokenResponseContent,
	CreateAccountExportResponseContent,
	CreateBoardRequestContent,
	CreateBoardResponseContent,
	CreateCardReactionRequestContent,
	CreateCardReactionResponseContent,
	CreateCardRequestContent,
	CreateCardResponseContent,
	CreateColumnRequestContent,
	CreateColumnResponseContent,
	CreateCommentReactionRequestContent,
	CreateCommentReactionResponseContent,
	CreateCommentRequestContent,
	CreateCommentResponseContent,
	CreateDirectUploadRequestContent,
	CreateDirectUploadResponseContent,
	CreatePushSubscriptionRequestContent,
	CreateSessionRequestContent,
	CreateSessionResponseContent,
	CreateStepRequestContent,
	CreateStepResponseContent,
	CreateUserDataExportResponseContent,
	CreateWebhookRequestContent,
	CreateWebhookResponseContent,
	GetAccountExportResponseContent,
	GetAccountSettingsResponseContent,
	GetBoardResponseContent,
	GetCardResponseContent,
	GetColumnResponseContent,
	GetCommentResponseContent,
	GetJoinCodeResponseContent,
	GetMyIdentityResponseContent,
	GetNotificationSettingsResponseContent,
	GetNotificationTrayResponseContent,
	GetStepResponseContent,
	GetUserDataExportResponseContent,
	GetUserResponseContent,
	GetWebhookResponseContent,
	ListAccessTokensResponseContent,
	ListActivitiesResponseContent,
	ListBoardAccessesResponseContent,
	ListBoardsResponseContent,
	ListCardReactionsResponseContent,
	ListCardsResponseContent,
	ListClosedCardsResponseContent,
	ListColumnCardsResponseContent,
	ListColumnsResponseContent,
	ListCommentReactionsResponseContent,
	ListCommentsResponseContent,
	ListNotificationsResponseContent,
	ListPinsResponseContent,
	ListPostponedCardsResponseContent,
	ListStepsResponseContent,
	ListStreamCardsResponseContent,
	ListTagsResponseContent,
	ListUsersResponseContent,
	ListWebhookDeliveriesResponseContent,
	ListWebhooksResponseContent,
	MoveCardRequestContent,
	MoveCardResponseContent,
	RedeemMagicLinkRequestContent,
	RedeemMagicLinkResponseContent,
	RegisterDeviceRequestContent,
	RequestEmailAddressChangeRequestContent,
	SearchCardsResponseContent,
	TagCardRequestContent,
	TriageCardRequestContent,
	UpdateAccountEntropyRequestContent,
	UpdateAccountEntropyResponseContent,
	UpdateAccountSettingsRequestContent,
	UpdateBoardEntropyRequestContent,
	UpdateBoardEntropyResponseContent,
	UpdateBoardInvolvementRequestContent,
	UpdateBoardRequestContent,
	UpdateBoardResponseContent,
	UpdateCardRequestContent,
	UpdateCardResponseContent,
	UpdateColumnRequestContent,
	UpdateColumnResponseContent,
	UpdateCommentRequestContent,
	UpdateCommentResponseContent,
	UpdateJoinCodeRequestContent,
	UpdateMyTimezoneRequestContent,
	UpdateNotificationSettingsRequestContent,
	UpdateStepRequestContent,
	UpdateStepResponseContent,
	UpdateUserRequestContent,
	UpdateUserResponseContent,
	UpdateUserRoleRequestContent,
	UpdateWebhookRequestContent,
	UpdateWebhookResponseContent,
} from "./types";

export interface BaseParams {
	[key: string]: unknown;
}

export function listAccessTokens(): Effect.Effect<
	ListAccessTokensResponseContent,
	EffectHttpClientError,
	HttpClient.HttpClient
> {
	return execute<ListAccessTokensResponseContent>("GET", `/my/access_tokens.json`);
}
/**
 * @param data - Request body
 */
export function createAccessToken(
	data: CreateAccessTokenRequestContent,
): Effect.Effect<CreateAccessTokenResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<CreateAccessTokenResponseContent, CreateAccessTokenRequestContent>(
		"POST",
		`/my/access_tokens.json`,
		{ body: data },
	);
}
export interface DeleteAccessTokenPathParams extends BaseParams {
	accessTokenId: string;
}
export function deleteAccessToken(
	params: DeleteAccessTokenPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/my/access_tokens/${params.accessTokenId}`);
}
export function getMyIdentity(): Effect.Effect<
	GetMyIdentityResponseContent,
	EffectHttpClientError,
	HttpClient.HttpClient
> {
	return execute<GetMyIdentityResponseContent>("GET", `/my/identity.json`);
}
export function destroySession(): Effect.Effect<
	void,
	EffectHttpClientError,
	HttpClient.HttpClient
> {
	return execute<void>("DELETE", `/session.json`);
}
/**
 * @param data - Request body
 */
export function createSession(
	data: CreateSessionRequestContent,
): Effect.Effect<CreateSessionResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<CreateSessionResponseContent, CreateSessionRequestContent>(
		"POST",
		`/session.json`,
		{ body: data },
	);
}
/**
 * @param data - Request body
 */
export function redeemMagicLink(
	data: RedeemMagicLinkRequestContent,
): Effect.Effect<RedeemMagicLinkResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<RedeemMagicLinkResponseContent, RedeemMagicLinkRequestContent>(
		"POST",
		`/session/magic_link.json`,
		{ body: data },
	);
}
/**
 * @param data - Request body
 */
export function completeSignup(
	data: CompleteSignupRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, CompleteSignupRequestContent>("POST", `/signup/completion.json`, {
		body: data,
	});
}
/**
 * @param data - Request body
 */
export function completeJoin(
	data: CompleteJoinRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, CompleteJoinRequestContent>("POST", `/users/joins.json`, { body: data });
}
export interface UpdateAccountEntropyPathParams extends BaseParams {
	accountId: string;
}
/**
 * @param data - Request body
 */
export function updateAccountEntropy(
	params: UpdateAccountEntropyPathParams,
	data: UpdateAccountEntropyRequestContent,
): Effect.Effect<
	UpdateAccountEntropyResponseContent,
	EffectHttpClientError,
	HttpClient.HttpClient
> {
	return execute<UpdateAccountEntropyResponseContent, UpdateAccountEntropyRequestContent>(
		"PUT",
		`/${params.accountId}/account/entropy.json`,
		{ body: data },
	);
}
export interface CreateAccountExportPathParams extends BaseParams {
	accountId: string;
}
export function createAccountExport(
	params: CreateAccountExportPathParams,
): Effect.Effect<CreateAccountExportResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<CreateAccountExportResponseContent>(
		"POST",
		`/${params.accountId}/account/exports.json`,
	);
}
export interface GetAccountExportPathParams extends BaseParams {
	accountId: string;
	exportId: string;
}
export function getAccountExport(
	params: GetAccountExportPathParams,
): Effect.Effect<GetAccountExportResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetAccountExportResponseContent>(
		"GET",
		`/${params.accountId}/account/exports/${params.exportId}`,
	);
}
export interface ResetJoinCodePathParams extends BaseParams {
	accountId: string;
}
export function resetJoinCode(
	params: ResetJoinCodePathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/account/join_code.json`);
}
export interface GetJoinCodePathParams extends BaseParams {
	accountId: string;
}
export function getJoinCode(
	params: GetJoinCodePathParams,
): Effect.Effect<GetJoinCodeResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetJoinCodeResponseContent>("GET", `/${params.accountId}/account/join_code.json`);
}
export interface UpdateJoinCodePathParams extends BaseParams {
	accountId: string;
}
/**
 * @param data - Request body
 */
export function updateJoinCode(
	params: UpdateJoinCodePathParams,
	data: UpdateJoinCodeRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, UpdateJoinCodeRequestContent>(
		"PATCH",
		`/${params.accountId}/account/join_code.json`,
		{ body: data },
	);
}
export interface GetAccountSettingsPathParams extends BaseParams {
	accountId: string;
}
export function getAccountSettings(
	params: GetAccountSettingsPathParams,
): Effect.Effect<GetAccountSettingsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetAccountSettingsResponseContent>(
		"GET",
		`/${params.accountId}/account/settings.json`,
	);
}
export interface UpdateAccountSettingsPathParams extends BaseParams {
	accountId: string;
}
/**
 * @param data - Request body
 */
export function updateAccountSettings(
	params: UpdateAccountSettingsPathParams,
	data: UpdateAccountSettingsRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, UpdateAccountSettingsRequestContent>(
		"PATCH",
		`/${params.accountId}/account/settings.json`,
		{ body: data },
	);
}
export interface ListActivitiesPathParams extends BaseParams {
	accountId: string;
}
export interface ListActivitiesQueryParams extends BaseParams {
	"creator_ids[]"?: string[];
	"board_ids[]"?: string[];
}
export function listActivities(
	params: ListActivitiesPathParams,
	query?: ListActivitiesQueryParams,
): Effect.Effect<ListActivitiesResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListActivitiesResponseContent>("GET", `/${params.accountId}/activities.json`, {
		query,
	});
}
export interface ListBoardsPathParams extends BaseParams {
	accountId: string;
}
export function listBoards(
	params: ListBoardsPathParams,
): Effect.Effect<ListBoardsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListBoardsResponseContent>("GET", `/${params.accountId}/boards.json`);
}
export interface CreateBoardPathParams extends BaseParams {
	accountId: string;
}
/**
 * @param data - Request body
 */
export function createBoard(
	params: CreateBoardPathParams,
	data: CreateBoardRequestContent,
): Effect.Effect<CreateBoardResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<CreateBoardResponseContent, CreateBoardRequestContent>(
		"POST",
		`/${params.accountId}/boards.json`,
		{ body: data },
	);
}
export interface DeleteBoardPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
export function deleteBoard(
	params: DeleteBoardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/boards/${params.boardId}`);
}
export interface GetBoardPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
export function getBoard(
	params: GetBoardPathParams,
): Effect.Effect<GetBoardResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetBoardResponseContent>("GET", `/${params.accountId}/boards/${params.boardId}`);
}
export interface UpdateBoardPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
/**
 * @param data - Request body
 */
export function updateBoard(
	params: UpdateBoardPathParams,
	data: UpdateBoardRequestContent,
): Effect.Effect<UpdateBoardResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<UpdateBoardResponseContent, UpdateBoardRequestContent>(
		"PATCH",
		`/${params.accountId}/boards/${params.boardId}`,
		{ body: data },
	);
}
export interface ListBoardAccessesPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
export interface ListBoardAccessesQueryParams extends BaseParams {
	page?: number;
}
export function listBoardAccesses(
	params: ListBoardAccessesPathParams,
	query?: ListBoardAccessesQueryParams,
): Effect.Effect<ListBoardAccessesResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListBoardAccessesResponseContent>(
		"GET",
		`/${params.accountId}/boards/${params.boardId}/accesses.json`,
		{ query },
	);
}
export interface ListColumnsPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
export function listColumns(
	params: ListColumnsPathParams,
): Effect.Effect<ListColumnsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListColumnsResponseContent>(
		"GET",
		`/${params.accountId}/boards/${params.boardId}/columns.json`,
	);
}
export interface CreateColumnPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
/**
 * @param data - Request body
 */
export function createColumn(
	params: CreateColumnPathParams,
	data: CreateColumnRequestContent,
): Effect.Effect<CreateColumnResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<CreateColumnResponseContent, CreateColumnRequestContent>(
		"POST",
		`/${params.accountId}/boards/${params.boardId}/columns.json`,
		{ body: data },
	);
}
export interface ListClosedCardsPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
export function listClosedCards(
	params: ListClosedCardsPathParams,
): Effect.Effect<ListClosedCardsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListClosedCardsResponseContent>(
		"GET",
		`/${params.accountId}/boards/${params.boardId}/columns/closed.json`,
	);
}
export interface ListPostponedCardsPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
export function listPostponedCards(
	params: ListPostponedCardsPathParams,
): Effect.Effect<ListPostponedCardsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListPostponedCardsResponseContent>(
		"GET",
		`/${params.accountId}/boards/${params.boardId}/columns/not_now.json`,
	);
}
export interface ListStreamCardsPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
export function listStreamCards(
	params: ListStreamCardsPathParams,
): Effect.Effect<ListStreamCardsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListStreamCardsResponseContent>(
		"GET",
		`/${params.accountId}/boards/${params.boardId}/columns/stream.json`,
	);
}
export interface DeleteColumnPathParams extends BaseParams {
	accountId: string;
	boardId: string;
	columnId: string;
}
export function deleteColumn(
	params: DeleteColumnPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"DELETE",
		`/${params.accountId}/boards/${params.boardId}/columns/${params.columnId}`,
	);
}
export interface GetColumnPathParams extends BaseParams {
	accountId: string;
	boardId: string;
	columnId: string;
}
export function getColumn(
	params: GetColumnPathParams,
): Effect.Effect<GetColumnResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetColumnResponseContent>(
		"GET",
		`/${params.accountId}/boards/${params.boardId}/columns/${params.columnId}`,
	);
}
export interface UpdateColumnPathParams extends BaseParams {
	accountId: string;
	boardId: string;
	columnId: string;
}
/**
 * @param data - Request body
 */
export function updateColumn(
	params: UpdateColumnPathParams,
	data: UpdateColumnRequestContent,
): Effect.Effect<UpdateColumnResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<UpdateColumnResponseContent, UpdateColumnRequestContent>(
		"PATCH",
		`/${params.accountId}/boards/${params.boardId}/columns/${params.columnId}`,
		{ body: data },
	);
}
export interface ListColumnCardsPathParams extends BaseParams {
	accountId: string;
	boardId: string;
	columnId: string;
}
export function listColumnCards(
	params: ListColumnCardsPathParams,
): Effect.Effect<ListColumnCardsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListColumnCardsResponseContent>(
		"GET",
		`/${params.accountId}/boards/${params.boardId}/columns/${params.columnId}/cards.json`,
	);
}
export interface UpdateBoardEntropyPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
/**
 * @param data - Request body
 */
export function updateBoardEntropy(
	params: UpdateBoardEntropyPathParams,
	data: UpdateBoardEntropyRequestContent,
): Effect.Effect<UpdateBoardEntropyResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<UpdateBoardEntropyResponseContent, UpdateBoardEntropyRequestContent>(
		"PUT",
		`/${params.accountId}/boards/${params.boardId}/entropy.json`,
		{ body: data },
	);
}
export interface UpdateBoardInvolvementPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
/**
 * @param data - Request body
 */
export function updateBoardInvolvement(
	params: UpdateBoardInvolvementPathParams,
	data: UpdateBoardInvolvementRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, UpdateBoardInvolvementRequestContent>(
		"PATCH",
		`/${params.accountId}/boards/${params.boardId}/involvement.json`,
		{ body: data },
	);
}
export interface UnpublishBoardPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
export function unpublishBoard(
	params: UnpublishBoardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/boards/${params.boardId}/publication.json`);
}
export interface PublishBoardPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
export function publishBoard(
	params: PublishBoardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("POST", `/${params.accountId}/boards/${params.boardId}/publication.json`);
}
export interface ListWebhooksPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
export function listWebhooks(
	params: ListWebhooksPathParams,
): Effect.Effect<ListWebhooksResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListWebhooksResponseContent>(
		"GET",
		`/${params.accountId}/boards/${params.boardId}/webhooks.json`,
	);
}
export interface CreateWebhookPathParams extends BaseParams {
	accountId: string;
	boardId: string;
}
/**
 * @param data - Request body
 */
export function createWebhook(
	params: CreateWebhookPathParams,
	data: CreateWebhookRequestContent,
): Effect.Effect<CreateWebhookResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<CreateWebhookResponseContent, CreateWebhookRequestContent>(
		"POST",
		`/${params.accountId}/boards/${params.boardId}/webhooks.json`,
		{ body: data },
	);
}
export interface DeleteWebhookPathParams extends BaseParams {
	accountId: string;
	boardId: string;
	webhookId: string;
}
export function deleteWebhook(
	params: DeleteWebhookPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"DELETE",
		`/${params.accountId}/boards/${params.boardId}/webhooks/${params.webhookId}`,
	);
}
export interface GetWebhookPathParams extends BaseParams {
	accountId: string;
	boardId: string;
	webhookId: string;
}
export function getWebhook(
	params: GetWebhookPathParams,
): Effect.Effect<GetWebhookResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetWebhookResponseContent>(
		"GET",
		`/${params.accountId}/boards/${params.boardId}/webhooks/${params.webhookId}`,
	);
}
export interface UpdateWebhookPathParams extends BaseParams {
	accountId: string;
	boardId: string;
	webhookId: string;
}
/**
 * @param data - Request body
 */
export function updateWebhook(
	params: UpdateWebhookPathParams,
	data: UpdateWebhookRequestContent,
): Effect.Effect<UpdateWebhookResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<UpdateWebhookResponseContent, UpdateWebhookRequestContent>(
		"PATCH",
		`/${params.accountId}/boards/${params.boardId}/webhooks/${params.webhookId}`,
		{ body: data },
	);
}
export interface ActivateWebhookPathParams extends BaseParams {
	accountId: string;
	boardId: string;
	webhookId: string;
}
export function activateWebhook(
	params: ActivateWebhookPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"POST",
		`/${params.accountId}/boards/${params.boardId}/webhooks/${params.webhookId}/activation.json`,
	);
}
export interface ListWebhookDeliveriesPathParams extends BaseParams {
	accountId: string;
	boardId: string;
	webhookId: string;
}
export function listWebhookDeliveries(
	params: ListWebhookDeliveriesPathParams,
): Effect.Effect<
	ListWebhookDeliveriesResponseContent,
	EffectHttpClientError,
	HttpClient.HttpClient
> {
	return execute<ListWebhookDeliveriesResponseContent>(
		"GET",
		`/${params.accountId}/boards/${params.boardId}/webhooks/${params.webhookId}/deliveries.json`,
	);
}
export interface ListCardsPathParams extends BaseParams {
	accountId: string;
}
export interface ListCardsQueryParams extends BaseParams {
	"board_ids[]"?: string[];
	"tag_ids[]"?: string[];
	"assignee_ids[]"?: string[];
	"creator_ids[]"?: string[];
	"closer_ids[]"?: string[];
	"card_ids[]"?: string[];
	"column_ids[]"?: string[];
	indexed_by?: string;
	sorted_by?: string;
	assignment_status?: string;
	creation?: string;
	closure?: string;
	"terms[]"?: string[];
}
export function listCards(
	params: ListCardsPathParams,
	query?: ListCardsQueryParams,
): Effect.Effect<ListCardsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListCardsResponseContent>("GET", `/${params.accountId}/cards.json`, { query });
}
export interface CreateCardPathParams extends BaseParams {
	accountId: string;
}
/**
 * @param data - Request body
 */
export function createCard(
	params: CreateCardPathParams,
	data: CreateCardRequestContent,
): Effect.Effect<CreateCardResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<CreateCardResponseContent, CreateCardRequestContent>(
		"POST",
		`/${params.accountId}/cards.json`,
		{ body: data },
	);
}
export interface DeleteCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function deleteCard(
	params: DeleteCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/cards/${params.cardNumber}`);
}
export interface GetCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function getCard(
	params: GetCardPathParams,
): Effect.Effect<GetCardResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetCardResponseContent>("GET", `/${params.accountId}/cards/${params.cardNumber}`);
}
export interface UpdateCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
/**
 * @param data - Request body
 */
export function updateCard(
	params: UpdateCardPathParams,
	data: UpdateCardRequestContent,
): Effect.Effect<UpdateCardResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<UpdateCardResponseContent, UpdateCardRequestContent>(
		"PATCH",
		`/${params.accountId}/cards/${params.cardNumber}`,
		{ body: data },
	);
}
export interface AssignCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
/**
 * @param data - Request body
 */
export function assignCard(
	params: AssignCardPathParams,
	data: AssignCardRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, AssignCardRequestContent>(
		"POST",
		`/${params.accountId}/cards/${params.cardNumber}/assignments.json`,
		{ body: data },
	);
}
export interface MoveCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
/**
 * @param data - Request body
 */
export function moveCard(
	params: MoveCardPathParams,
	data: MoveCardRequestContent,
): Effect.Effect<MoveCardResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<MoveCardResponseContent, MoveCardRequestContent>(
		"PATCH",
		`/${params.accountId}/cards/${params.cardNumber}/board.json`,
		{ body: data },
	);
}
export interface ReopenCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function reopenCard(
	params: ReopenCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/cards/${params.cardNumber}/closure.json`);
}
export interface CloseCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function closeCard(
	params: CloseCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("POST", `/${params.accountId}/cards/${params.cardNumber}/closure.json`);
}
export interface ListCommentsPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function listComments(
	params: ListCommentsPathParams,
): Effect.Effect<ListCommentsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListCommentsResponseContent>(
		"GET",
		`/${params.accountId}/cards/${params.cardNumber}/comments.json`,
	);
}
export interface CreateCommentPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
/**
 * @param data - Request body
 */
export function createComment(
	params: CreateCommentPathParams,
	data: CreateCommentRequestContent,
): Effect.Effect<CreateCommentResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<CreateCommentResponseContent, CreateCommentRequestContent>(
		"POST",
		`/${params.accountId}/cards/${params.cardNumber}/comments.json`,
		{ body: data },
	);
}
export interface DeleteCommentPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
	commentId: string;
}
export function deleteComment(
	params: DeleteCommentPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"DELETE",
		`/${params.accountId}/cards/${params.cardNumber}/comments/${params.commentId}`,
	);
}
export interface GetCommentPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
	commentId: string;
}
export function getComment(
	params: GetCommentPathParams,
): Effect.Effect<GetCommentResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetCommentResponseContent>(
		"GET",
		`/${params.accountId}/cards/${params.cardNumber}/comments/${params.commentId}`,
	);
}
export interface UpdateCommentPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
	commentId: string;
}
/**
 * @param data - Request body
 */
export function updateComment(
	params: UpdateCommentPathParams,
	data: UpdateCommentRequestContent,
): Effect.Effect<UpdateCommentResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<UpdateCommentResponseContent, UpdateCommentRequestContent>(
		"PATCH",
		`/${params.accountId}/cards/${params.cardNumber}/comments/${params.commentId}`,
		{ body: data },
	);
}
export interface ListCommentReactionsPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
	commentId: string;
}
export function listCommentReactions(
	params: ListCommentReactionsPathParams,
): Effect.Effect<
	ListCommentReactionsResponseContent,
	EffectHttpClientError,
	HttpClient.HttpClient
> {
	return execute<ListCommentReactionsResponseContent>(
		"GET",
		`/${params.accountId}/cards/${params.cardNumber}/comments/${params.commentId}/reactions.json`,
	);
}
export interface CreateCommentReactionPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
	commentId: string;
}
/**
 * @param data - Request body
 */
export function createCommentReaction(
	params: CreateCommentReactionPathParams,
	data: CreateCommentReactionRequestContent,
): Effect.Effect<
	CreateCommentReactionResponseContent,
	EffectHttpClientError,
	HttpClient.HttpClient
> {
	return execute<CreateCommentReactionResponseContent, CreateCommentReactionRequestContent>(
		"POST",
		`/${params.accountId}/cards/${params.cardNumber}/comments/${params.commentId}/reactions.json`,
		{ body: data },
	);
}
export interface DeleteCommentReactionPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
	commentId: string;
	reactionId: string;
}
export function deleteCommentReaction(
	params: DeleteCommentReactionPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"DELETE",
		`/${params.accountId}/cards/${params.cardNumber}/comments/${params.commentId}/reactions/${params.reactionId}`,
	);
}
export interface UngoldCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function ungoldCard(
	params: UngoldCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/cards/${params.cardNumber}/goldness.json`);
}
export interface GoldCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function goldCard(
	params: GoldCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("POST", `/${params.accountId}/cards/${params.cardNumber}/goldness.json`);
}
export interface DeleteCardImagePathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function deleteCardImage(
	params: DeleteCardImagePathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/cards/${params.cardNumber}/image.json`);
}
export interface PostponeCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function postponeCard(
	params: PostponeCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("POST", `/${params.accountId}/cards/${params.cardNumber}/not_now.json`);
}
export interface UnpinCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function unpinCard(
	params: UnpinCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/cards/${params.cardNumber}/pin.json`);
}
export interface PinCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function pinCard(
	params: PinCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("POST", `/${params.accountId}/cards/${params.cardNumber}/pin.json`);
}
export interface PublishCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function publishCard(
	params: PublishCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("POST", `/${params.accountId}/cards/${params.cardNumber}/publish.json`);
}
export interface ListCardReactionsPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function listCardReactions(
	params: ListCardReactionsPathParams,
): Effect.Effect<ListCardReactionsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListCardReactionsResponseContent>(
		"GET",
		`/${params.accountId}/cards/${params.cardNumber}/reactions.json`,
	);
}
export interface CreateCardReactionPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
/**
 * @param data - Request body
 */
export function createCardReaction(
	params: CreateCardReactionPathParams,
	data: CreateCardReactionRequestContent,
): Effect.Effect<CreateCardReactionResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<CreateCardReactionResponseContent, CreateCardReactionRequestContent>(
		"POST",
		`/${params.accountId}/cards/${params.cardNumber}/reactions.json`,
		{ body: data },
	);
}
export interface DeleteCardReactionPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
	reactionId: string;
}
export function deleteCardReaction(
	params: DeleteCardReactionPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"DELETE",
		`/${params.accountId}/cards/${params.cardNumber}/reactions/${params.reactionId}`,
	);
}
export interface MarkCardUnreadPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function markCardUnread(
	params: MarkCardUnreadPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/cards/${params.cardNumber}/reading.json`);
}
export interface MarkCardReadPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function markCardRead(
	params: MarkCardReadPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("POST", `/${params.accountId}/cards/${params.cardNumber}/reading.json`);
}
export interface SelfAssignCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function selfAssignCard(
	params: SelfAssignCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"POST",
		`/${params.accountId}/cards/${params.cardNumber}/self_assignment.json`,
	);
}
export interface ListStepsPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function listSteps(
	params: ListStepsPathParams,
): Effect.Effect<ListStepsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListStepsResponseContent>(
		"GET",
		`/${params.accountId}/cards/${params.cardNumber}/steps.json`,
	);
}
export interface CreateStepPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
/**
 * @param data - Request body
 */
export function createStep(
	params: CreateStepPathParams,
	data: CreateStepRequestContent,
): Effect.Effect<CreateStepResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<CreateStepResponseContent, CreateStepRequestContent>(
		"POST",
		`/${params.accountId}/cards/${params.cardNumber}/steps.json`,
		{ body: data },
	);
}
export interface DeleteStepPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
	stepId: string;
}
export function deleteStep(
	params: DeleteStepPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"DELETE",
		`/${params.accountId}/cards/${params.cardNumber}/steps/${params.stepId}`,
	);
}
export interface GetStepPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
	stepId: string;
}
export function getStep(
	params: GetStepPathParams,
): Effect.Effect<GetStepResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetStepResponseContent>(
		"GET",
		`/${params.accountId}/cards/${params.cardNumber}/steps/${params.stepId}`,
	);
}
export interface UpdateStepPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
	stepId: string;
}
/**
 * @param data - Request body
 */
export function updateStep(
	params: UpdateStepPathParams,
	data: UpdateStepRequestContent,
): Effect.Effect<UpdateStepResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<UpdateStepResponseContent, UpdateStepRequestContent>(
		"PATCH",
		`/${params.accountId}/cards/${params.cardNumber}/steps/${params.stepId}`,
		{ body: data },
	);
}
export interface TagCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
/**
 * @param data - Request body
 */
export function tagCard(
	params: TagCardPathParams,
	data: TagCardRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, TagCardRequestContent>(
		"POST",
		`/${params.accountId}/cards/${params.cardNumber}/taggings.json`,
		{ body: data },
	);
}
export interface UnTriageCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function unTriageCard(
	params: UnTriageCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/cards/${params.cardNumber}/triage.json`);
}
export interface TriageCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
/**
 * @param data - Request body
 */
export function triageCard(
	params: TriageCardPathParams,
	data: TriageCardRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, TriageCardRequestContent>(
		"POST",
		`/${params.accountId}/cards/${params.cardNumber}/triage.json`,
		{ body: data },
	);
}
export interface UnwatchCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function unwatchCard(
	params: UnwatchCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/cards/${params.cardNumber}/watch.json`);
}
export interface WatchCardPathParams extends BaseParams {
	accountId: string;
	cardNumber: number;
}
export function watchCard(
	params: WatchCardPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("POST", `/${params.accountId}/cards/${params.cardNumber}/watch.json`);
}
export interface MoveColumnLeftPathParams extends BaseParams {
	accountId: string;
	columnId: string;
}
export function moveColumnLeft(
	params: MoveColumnLeftPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"POST",
		`/${params.accountId}/columns/${params.columnId}/left_position.json`,
	);
}
export interface MoveColumnRightPathParams extends BaseParams {
	accountId: string;
	columnId: string;
}
export function moveColumnRight(
	params: MoveColumnRightPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"POST",
		`/${params.accountId}/columns/${params.columnId}/right_position.json`,
	);
}
export interface RegisterDevicePathParams extends BaseParams {
	accountId: string;
}
/**
 * @param data - Request body
 */
export function registerDevice(
	params: RegisterDevicePathParams,
	data: RegisterDeviceRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, RegisterDeviceRequestContent>("POST", `/${params.accountId}/devices`, {
		body: data,
	});
}
export interface UnregisterDevicePathParams extends BaseParams {
	accountId: string;
	deviceToken: string;
}
export function unregisterDevice(
	params: UnregisterDevicePathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/devices/${params.deviceToken}`);
}
export interface ListPinsPathParams extends BaseParams {
	accountId: string;
}
export function listPins(
	params: ListPinsPathParams,
): Effect.Effect<ListPinsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListPinsResponseContent>("GET", `/${params.accountId}/my/pins.json`);
}
export interface UpdateMyTimezonePathParams extends BaseParams {
	accountId: string;
}
/**
 * @param data - Request body
 */
export function updateMyTimezone(
	params: UpdateMyTimezonePathParams,
	data: UpdateMyTimezoneRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, UpdateMyTimezoneRequestContent>(
		"PATCH",
		`/${params.accountId}/my/timezone.json`,
		{ body: data },
	);
}
export interface ListNotificationsPathParams extends BaseParams {
	accountId: string;
}
export interface ListNotificationsQueryParams extends BaseParams {
	read?: boolean;
}
export function listNotifications(
	params: ListNotificationsPathParams,
	query?: ListNotificationsQueryParams,
): Effect.Effect<ListNotificationsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListNotificationsResponseContent>(
		"GET",
		`/${params.accountId}/notifications.json`,
		{ query },
	);
}
export interface BulkReadNotificationsPathParams extends BaseParams {
	accountId: string;
}
/**
 * @param data - Request body
 */
export function bulkReadNotifications(
	params: BulkReadNotificationsPathParams,
	data: BulkReadNotificationsRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, BulkReadNotificationsRequestContent>(
		"POST",
		`/${params.accountId}/notifications/bulk_reading.json`,
		{ body: data },
	);
}
export interface GetNotificationSettingsPathParams extends BaseParams {
	accountId: string;
}
export function getNotificationSettings(
	params: GetNotificationSettingsPathParams,
): Effect.Effect<
	GetNotificationSettingsResponseContent,
	EffectHttpClientError,
	HttpClient.HttpClient
> {
	return execute<GetNotificationSettingsResponseContent>(
		"GET",
		`/${params.accountId}/notifications/settings.json`,
	);
}
export interface UpdateNotificationSettingsPathParams extends BaseParams {
	accountId: string;
}
/**
 * @param data - Request body
 */
export function updateNotificationSettings(
	params: UpdateNotificationSettingsPathParams,
	data: UpdateNotificationSettingsRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, UpdateNotificationSettingsRequestContent>(
		"PATCH",
		`/${params.accountId}/notifications/settings.json`,
		{ body: data },
	);
}
export interface GetNotificationTrayPathParams extends BaseParams {
	accountId: string;
}
export interface GetNotificationTrayQueryParams extends BaseParams {
	include_read?: boolean;
}
export function getNotificationTray(
	params: GetNotificationTrayPathParams,
	query?: GetNotificationTrayQueryParams,
): Effect.Effect<GetNotificationTrayResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetNotificationTrayResponseContent>(
		"GET",
		`/${params.accountId}/notifications/tray.json`,
		{ query },
	);
}
export interface UnreadNotificationPathParams extends BaseParams {
	accountId: string;
	notificationId: string;
}
export function unreadNotification(
	params: UnreadNotificationPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"DELETE",
		`/${params.accountId}/notifications/${params.notificationId}/reading.json`,
	);
}
export interface ReadNotificationPathParams extends BaseParams {
	accountId: string;
	notificationId: string;
}
export function readNotification(
	params: ReadNotificationPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"POST",
		`/${params.accountId}/notifications/${params.notificationId}/reading.json`,
	);
}
export interface CreateDirectUploadPathParams extends BaseParams {
	accountId: string;
}
/**
 * @param data - Request body
 */
export function createDirectUpload(
	params: CreateDirectUploadPathParams,
	data: CreateDirectUploadRequestContent,
): Effect.Effect<CreateDirectUploadResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<CreateDirectUploadResponseContent, CreateDirectUploadRequestContent>(
		"POST",
		`/${params.accountId}/rails/active_storage/direct_uploads`,
		{ body: data },
	);
}
export interface SearchCardsPathParams extends BaseParams {
	accountId: string;
}
export interface SearchCardsQueryParams extends BaseParams {
	q: string;
}
export function searchCards(
	params: SearchCardsPathParams,
	query?: SearchCardsQueryParams,
): Effect.Effect<SearchCardsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<SearchCardsResponseContent>("GET", `/${params.accountId}/search.json`, { query });
}
export interface ListTagsPathParams extends BaseParams {
	accountId: string;
}
export function listTags(
	params: ListTagsPathParams,
): Effect.Effect<ListTagsResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListTagsResponseContent>("GET", `/${params.accountId}/tags.json`);
}
export interface ListUsersPathParams extends BaseParams {
	accountId: string;
}
export function listUsers(
	params: ListUsersPathParams,
): Effect.Effect<ListUsersResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<ListUsersResponseContent>("GET", `/${params.accountId}/users.json`);
}
export interface DeactivateUserPathParams extends BaseParams {
	accountId: string;
	userId: string;
}
export function deactivateUser(
	params: DeactivateUserPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/users/${params.userId}`);
}
export interface GetUserPathParams extends BaseParams {
	accountId: string;
	userId: string;
}
export function getUser(
	params: GetUserPathParams,
): Effect.Effect<GetUserResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetUserResponseContent>("GET", `/${params.accountId}/users/${params.userId}`);
}
export interface UpdateUserPathParams extends BaseParams {
	accountId: string;
	userId: string;
}
/**
 * @param data - Request body
 */
export function updateUser(
	params: UpdateUserPathParams,
	data: UpdateUserRequestContent,
): Effect.Effect<UpdateUserResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<UpdateUserResponseContent, UpdateUserRequestContent>(
		"PATCH",
		`/${params.accountId}/users/${params.userId}`,
		{ body: data },
	);
}
export interface DeleteUserAvatarPathParams extends BaseParams {
	accountId: string;
	userId: string;
}
export function deleteUserAvatar(
	params: DeleteUserAvatarPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>("DELETE", `/${params.accountId}/users/${params.userId}/avatar`);
}
export interface CreateUserDataExportPathParams extends BaseParams {
	accountId: string;
	userId: string;
}
export function createUserDataExport(
	params: CreateUserDataExportPathParams,
): Effect.Effect<
	CreateUserDataExportResponseContent,
	EffectHttpClientError,
	HttpClient.HttpClient
> {
	return execute<CreateUserDataExportResponseContent>(
		"POST",
		`/${params.accountId}/users/${params.userId}/data_exports.json`,
	);
}
export interface GetUserDataExportPathParams extends BaseParams {
	accountId: string;
	userId: string;
	exportId: string;
}
export function getUserDataExport(
	params: GetUserDataExportPathParams,
): Effect.Effect<GetUserDataExportResponseContent, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<GetUserDataExportResponseContent>(
		"GET",
		`/${params.accountId}/users/${params.userId}/data_exports/${params.exportId}`,
	);
}
export interface RequestEmailAddressChangePathParams extends BaseParams {
	accountId: string;
	userId: string;
}
/**
 * @param data - Request body
 */
export function requestEmailAddressChange(
	params: RequestEmailAddressChangePathParams,
	data: RequestEmailAddressChangeRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, RequestEmailAddressChangeRequestContent>(
		"POST",
		`/${params.accountId}/users/${params.userId}/email_addresses.json`,
		{ body: data },
	);
}
export interface ConfirmEmailAddressChangePathParams extends BaseParams {
	accountId: string;
	userId: string;
	emailAddressToken: string;
}
export function confirmEmailAddressChange(
	params: ConfirmEmailAddressChangePathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"POST",
		`/${params.accountId}/users/${params.userId}/email_addresses/${params.emailAddressToken}/confirmation.json`,
	);
}
export interface CreatePushSubscriptionPathParams extends BaseParams {
	accountId: string;
	userId: string;
}
/**
 * @param data - Request body
 */
export function createPushSubscription(
	params: CreatePushSubscriptionPathParams,
	data: CreatePushSubscriptionRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, CreatePushSubscriptionRequestContent>(
		"POST",
		`/${params.accountId}/users/${params.userId}/push_subscriptions.json`,
		{ body: data },
	);
}
export interface DeletePushSubscriptionPathParams extends BaseParams {
	accountId: string;
	userId: string;
	pushSubscriptionId: string;
}
export function deletePushSubscription(
	params: DeletePushSubscriptionPathParams,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void>(
		"DELETE",
		`/${params.accountId}/users/${params.userId}/push_subscriptions/${params.pushSubscriptionId}`,
	);
}
export interface UpdateUserRolePathParams extends BaseParams {
	accountId: string;
	userId: string;
}
/**
 * @param data - Request body
 */
export function updateUserRole(
	params: UpdateUserRolePathParams,
	data: UpdateUserRoleRequestContent,
): Effect.Effect<void, EffectHttpClientError, HttpClient.HttpClient> {
	return execute<void, UpdateUserRoleRequestContent>(
		"PATCH",
		`/${params.accountId}/users/${params.userId}/role.json`,
		{ body: data },
	);
}
