// Generated by fizzyx. Do not edit.

export interface AccessToken {
	id: string;
	description: string;
	permission: string;
	created_at: string;
	token?: string;
}
export interface Account {
	id: string;
	name: string;
	slug: string;
	created_at: string;
	url: string;
	user?: User;
}
export interface AccountExport {
	id: string;
	status: string;
	created_at: string;
	download_url?: string;
}
export interface AccountSettings {
	id: string;
	name: string;
	cards_count: number;
	created_at: string;
	auto_postpone_period_in_days?: number;
}
export interface Activity {
	id: string;
	action: string;
	created_at: string;
	description: string;
	particulars: ActivityParticulars;
	url: string;
	eventable_type: string;
	eventable: ActivityEventable;
	board: Board;
	creator: User;
}
export interface ActivityEventable {
	id: string;
	number?: number;
	title?: string;
	status?: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments?: boolean;
	tags?: string[];
	closed?: boolean;
	postponed?: boolean;
	golden?: boolean;
	last_active_at?: string;
	created_at?: string;
	updated_at?: string;
	body?: RichTextBody;
	creator?: User;
	card?: CardRef;
	board?: Board;
	column?: Column;
	assignees?: User[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: Step[];
	url: string;
}
export interface ActivityParticulars {
	assignee_ids?: string[];
	old_board?: string;
	new_board?: string;
	old_title?: string;
	new_title?: string;
	column?: string;
}
export interface AssignCardRequestContent {
	assignee_id: string;
}
export interface BadRequestErrorResponseContent {
	message: string;
}
export interface Board {
	id: string;
	name: string;
	all_access: boolean;
	created_at: string;
	auto_postpone_period_in_days?: number;
	public_description?: string;
	public_description_html?: string;
	public_url?: string;
	user_ids?: string[];
	url: string;
	creator?: User;
}
export interface BoardAccessUser {
	id: string;
	name: string;
	role: string;
	active: boolean;
	email_address: string;
	created_at: string;
	url: string;
	avatar_url?: string;
	has_access: boolean;
	involvement?: string;
}
export interface BoardAccesses {
	board_id: string;
	all_access: boolean;
	users: BoardAccessUser[];
}
export interface BulkReadNotificationsRequestContent {
	notification_ids?: string[];
}
export interface Card {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: Board;
	column?: Column;
	creator?: User;
	assignees?: User[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: Step[];
}
export interface CardRef {
	id: string;
	url: string;
}
export interface Color {
	name: string;
	value: string;
}
export interface Column {
	id: string;
	name: string;
	color?: Color;
	created_at: string;
	cards_url?: string;
}
export interface Comment {
	id: string;
	created_at: string;
	updated_at: string;
	body: RichTextBody;
	creator: User;
	card?: CardRef;
	reactions_url?: string;
	url: string;
}
export interface CompleteJoinRequestContent {
	name: string;
}
export interface CompleteSignupRequestContent {
	full_name: string;
}
export interface CreateAccessTokenRequestContent {
	description: string;
	permission: string;
}
export interface CreateAccessTokenResponseContent {
	id: string;
	description: string;
	permission: string;
	created_at: string;
	token?: string;
}
export interface CreateAccountExportResponseContent {
	id: string;
	status: string;
	created_at: string;
	download_url?: string;
}
export interface CreateBoardRequestContent {
	name: string;
	all_access?: boolean;
	auto_postpone_period_in_days?: number;
	public_description?: string;
}
export interface CreateBoardResponseContent {
	id: string;
	name: string;
	all_access: boolean;
	created_at: string;
	auto_postpone_period_in_days?: number;
	public_description?: string;
	public_description_html?: string;
	public_url?: string;
	user_ids?: string[];
	url: string;
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
}
export interface CreateCardReactionRequestContent {
	content: string;
}
export interface CreateCardReactionResponseContent {
	id: string;
	content: string;
	reacter: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	url: string;
}
export interface CreateCardRequestContent {
	title: string;
	board_id?: string;
	column_id?: string;
	description?: string;
	assignee_ids?: string[];
	tag_names?: string[];
	image?: string;
	created_at?: string;
	last_active_at?: string;
}
export interface CreateCardResponseContent {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	column?: {
		id: string;
		name: string;
		color?: { name: string; value: string };
		created_at: string;
		cards_url?: string;
	};
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	assignees?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	}[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: { id: string; content: string; completed: boolean }[];
}
export interface CreateColumnRequestContent {
	name: string;
	color?: string;
}
export interface CreateColumnResponseContent {
	id: string;
	name: string;
	color?: { name: string; value: string };
	created_at: string;
	cards_url?: string;
}
export interface CreateCommentReactionRequestContent {
	content: string;
}
export interface CreateCommentReactionResponseContent {
	id: string;
	content: string;
	reacter: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	url: string;
}
export interface CreateCommentRequestContent {
	body: string;
	created_at?: string;
}
export interface CreateCommentResponseContent {
	id: string;
	created_at: string;
	updated_at: string;
	body: { plain_text: string; html: string };
	creator: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	card?: { id: string; url: string };
	reactions_url?: string;
	url: string;
}
export interface CreateDirectUploadRequestContent {
	filename: string;
	content_type: string;
	byte_size: number;
	checksum: string;
}
export interface CreateDirectUploadResponseContent {
	id: string;
	key: string;
	filename: string;
	content_type: string;
	byte_size: number;
	checksum: string;
	direct_upload: { url: string; headers: { Content_Type: string; Content_MD5?: string } };
}
export interface CreatePushSubscriptionRequestContent {
	endpoint: string;
	p256dh_key: string;
	auth_key: string;
}
export interface CreateSessionRequestContent {
	email_address: string;
}
export interface CreateSessionResponseContent {
	pending_authentication_token: string;
}
export interface CreateStepRequestContent {
	content: string;
	completed?: boolean;
}
export interface CreateStepResponseContent {
	id: string;
	content: string;
	completed: boolean;
}
export interface CreateUserDataExportResponseContent {
	id: string;
	status: string;
	created_at: string;
	download_url?: string;
}
export interface CreateWebhookRequestContent {
	name: string;
	url: string;
	subscribed_actions?: string[];
}
export interface CreateWebhookResponseContent {
	id: string;
	name: string;
	payload_url: string;
	url: string;
	subscribed_actions: string[];
	signing_secret: string;
	active: boolean;
	created_at: string;
	updated_at?: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
}
export interface DataExport {
	id: string;
	status: string;
	created_at: string;
	download_url?: string;
}
export interface DirectUpload {
	id: string;
	key: string;
	filename: string;
	content_type: string;
	byte_size: number;
	checksum: string;
	direct_upload: DirectUploadMetadata;
}
export interface DirectUploadHeaders {
	Content_Type: string;
	Content_MD5?: string;
}
export interface DirectUploadMetadata {
	url: string;
	headers: DirectUploadHeaders;
}
export interface ForbiddenErrorResponseContent {
	message: string;
}
export interface GetAccountExportResponseContent {
	id: string;
	status: string;
	created_at: string;
	download_url?: string;
}
export interface GetAccountSettingsResponseContent {
	id: string;
	name: string;
	cards_count: number;
	created_at: string;
	auto_postpone_period_in_days?: number;
}
export interface GetBoardResponseContent {
	id: string;
	name: string;
	all_access: boolean;
	created_at: string;
	auto_postpone_period_in_days?: number;
	public_description?: string;
	public_description_html?: string;
	public_url?: string;
	user_ids?: string[];
	url: string;
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
}
export interface GetCardResponseContent {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	column?: {
		id: string;
		name: string;
		color?: { name: string; value: string };
		created_at: string;
		cards_url?: string;
	};
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	assignees?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	}[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: { id: string; content: string; completed: boolean }[];
}
export interface GetColumnResponseContent {
	id: string;
	name: string;
	color?: { name: string; value: string };
	created_at: string;
	cards_url?: string;
}
export interface GetCommentResponseContent {
	id: string;
	created_at: string;
	updated_at: string;
	body: { plain_text: string; html: string };
	creator: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	card?: { id: string; url: string };
	reactions_url?: string;
	url: string;
}
export interface GetJoinCodeResponseContent {
	code: string;
	url: string;
	usage_count?: number;
	usage_limit?: number;
	active?: boolean;
}
export interface GetMyIdentityResponseContent {
	id: string;
	name?: string;
	email_address?: string;
	accounts: {
		id: string;
		name: string;
		slug: string;
		created_at: string;
		url: string;
		user?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	}[];
}
export interface GetNotificationSettingsResponseContent {
	bundle_email_frequency: string;
}
export interface GetNotificationTrayResponseContent {
	id: string;
	unread_count: number;
	read: boolean;
	read_at?: string;
	created_at: string;
	source_type: string;
	title?: string;
	body?: string;
	creator: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	card?: {
		id: string;
		number: number;
		title: string;
		status: string;
		board_name?: string;
		closed: boolean;
		postponed: boolean;
		url: string;
		column?: {
			id: string;
			name: string;
			color?: { name: string; value: string };
			created_at: string;
			cards_url?: string;
		};
	};
	url: string;
}
export interface GetStepResponseContent {
	id: string;
	content: string;
	completed: boolean;
}
export interface GetUserDataExportResponseContent {
	id: string;
	status: string;
	created_at: string;
	download_url?: string;
}
export interface GetUserResponseContent {
	id: string;
	name: string;
	role: string;
	active: boolean;
	email_address: string;
	created_at: string;
	url: string;
	avatar_url?: string;
}
export interface GetWebhookResponseContent {
	id: string;
	name: string;
	payload_url: string;
	url: string;
	subscribed_actions: string[];
	signing_secret: string;
	active: boolean;
	created_at: string;
	updated_at?: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
}
export interface Identity {
	id: string;
	name?: string;
	email_address?: string;
	accounts: Account[];
}
export interface InternalServerErrorResponseContent {
	message: string;
}
export interface JoinCode {
	code: string;
	url: string;
	usage_count?: number;
	usage_limit?: number;
	active?: boolean;
}
export interface ListAccessTokensResponseContent {
	id: string;
	description: string;
	permission: string;
	created_at: string;
	token?: string;
}
export interface ListActivitiesResponseContent {
	id: string;
	action: string;
	created_at: string;
	description: string;
	particulars: {
		assignee_ids?: string[];
		old_board?: string;
		new_board?: string;
		old_title?: string;
		new_title?: string;
		column?: string;
	};
	url: string;
	eventable_type: string;
	eventable: {
		id: string;
		number?: number;
		title?: string;
		status?: string;
		description?: string;
		description_html?: string;
		image_url?: string;
		has_attachments?: boolean;
		tags?: string[];
		closed?: boolean;
		postponed?: boolean;
		golden?: boolean;
		last_active_at?: string;
		created_at?: string;
		updated_at?: string;
		body?: { plain_text: string; html: string };
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
		card?: { id: string; url: string };
		board?: {
			id: string;
			name: string;
			all_access: boolean;
			created_at: string;
			auto_postpone_period_in_days?: number;
			public_description?: string;
			public_description_html?: string;
			public_url?: string;
			user_ids?: string[];
			url: string;
			creator?: {
				id: string;
				name: string;
				role: string;
				active: boolean;
				email_address: string;
				created_at: string;
				url: string;
				avatar_url?: string;
			};
		};
		column?: {
			id: string;
			name: string;
			color?: { name: string; value: string };
			created_at: string;
			cards_url?: string;
		};
		assignees?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		}[];
		has_more_assignees?: boolean;
		comments_url?: string;
		reactions_url?: string;
		steps?: { id: string; content: string; completed: boolean }[];
		url: string;
	};
	board: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	creator: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
}
export interface ListBoardAccessesResponseContent {
	board_id: string;
	all_access: boolean;
	users: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
		has_access: boolean;
		involvement?: string;
	}[];
}
export interface ListBoardsResponseContent {
	id: string;
	name: string;
	all_access: boolean;
	created_at: string;
	auto_postpone_period_in_days?: number;
	public_description?: string;
	public_description_html?: string;
	public_url?: string;
	user_ids?: string[];
	url: string;
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
}
export interface ListCardReactionsResponseContent {
	id: string;
	content: string;
	reacter: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	url: string;
}
export interface ListCardsResponseContent {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	column?: {
		id: string;
		name: string;
		color?: { name: string; value: string };
		created_at: string;
		cards_url?: string;
	};
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	assignees?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	}[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: { id: string; content: string; completed: boolean }[];
}
export interface ListClosedCardsResponseContent {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	column?: {
		id: string;
		name: string;
		color?: { name: string; value: string };
		created_at: string;
		cards_url?: string;
	};
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	assignees?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	}[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: { id: string; content: string; completed: boolean }[];
}
export interface ListColumnCardsResponseContent {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	column?: {
		id: string;
		name: string;
		color?: { name: string; value: string };
		created_at: string;
		cards_url?: string;
	};
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	assignees?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	}[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: { id: string; content: string; completed: boolean }[];
}
export interface ListColumnsResponseContent {
	id: string;
	name: string;
	color?: { name: string; value: string };
	created_at: string;
	cards_url?: string;
}
export interface ListCommentReactionsResponseContent {
	id: string;
	content: string;
	reacter: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	url: string;
}
export interface ListCommentsResponseContent {
	id: string;
	created_at: string;
	updated_at: string;
	body: { plain_text: string; html: string };
	creator: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	card?: { id: string; url: string };
	reactions_url?: string;
	url: string;
}
export interface ListNotificationsResponseContent {
	id: string;
	unread_count: number;
	read: boolean;
	read_at?: string;
	created_at: string;
	source_type: string;
	title?: string;
	body?: string;
	creator: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	card?: {
		id: string;
		number: number;
		title: string;
		status: string;
		board_name?: string;
		closed: boolean;
		postponed: boolean;
		url: string;
		column?: {
			id: string;
			name: string;
			color?: { name: string; value: string };
			created_at: string;
			cards_url?: string;
		};
	};
	url: string;
}
export interface ListPinsResponseContent {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	column?: {
		id: string;
		name: string;
		color?: { name: string; value: string };
		created_at: string;
		cards_url?: string;
	};
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	assignees?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	}[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: { id: string; content: string; completed: boolean }[];
}
export interface ListPostponedCardsResponseContent {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	column?: {
		id: string;
		name: string;
		color?: { name: string; value: string };
		created_at: string;
		cards_url?: string;
	};
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	assignees?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	}[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: { id: string; content: string; completed: boolean }[];
}
export interface ListStepsResponseContent {
	id: string;
	content: string;
	completed: boolean;
}
export interface ListStreamCardsResponseContent {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	column?: {
		id: string;
		name: string;
		color?: { name: string; value: string };
		created_at: string;
		cards_url?: string;
	};
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	assignees?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	}[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: { id: string; content: string; completed: boolean }[];
}
export interface ListTagsResponseContent {
	id: string;
	title: string;
	created_at: string;
	url?: string;
}
export interface ListUsersResponseContent {
	id: string;
	name: string;
	role: string;
	active: boolean;
	email_address: string;
	created_at: string;
	url: string;
	avatar_url?: string;
}
export interface ListWebhookDeliveriesResponseContent {
	id: string;
	state: string;
	created_at: string;
	updated_at: string;
	request?: { headers?: Record<string, string> };
	response?: { code?: number; error?: string };
	event?: {
		id: string;
		action: string;
		created_at: string;
		creator?: { id: string; name: string };
		eventable?: { type: string; id: string; url: string };
	};
}
export interface ListWebhooksResponseContent {
	id: string;
	name: string;
	payload_url: string;
	url: string;
	subscribed_actions: string[];
	signing_secret: string;
	active: boolean;
	created_at: string;
	updated_at?: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
}
export interface MoveCardRequestContent {
	board_id: string;
	column_id?: string;
}
export interface MoveCardResponseContent {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	column?: {
		id: string;
		name: string;
		color?: { name: string; value: string };
		created_at: string;
		cards_url?: string;
	};
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	assignees?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	}[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: { id: string; content: string; completed: boolean }[];
}
export interface NotFoundErrorResponseContent {
	message: string;
}
export interface Notification {
	id: string;
	unread_count: number;
	read: boolean;
	read_at?: string;
	created_at: string;
	source_type: string;
	title?: string;
	body?: string;
	creator: User;
	card?: NotificationCard;
	url: string;
}
export interface NotificationCard {
	id: string;
	number: number;
	title: string;
	status: string;
	board_name?: string;
	closed: boolean;
	postponed: boolean;
	url: string;
	column?: Column;
}
export interface NotificationSettings {
	bundle_email_frequency: string;
}
export interface PendingAuthentication {
	pending_authentication_token: string;
}
export interface RateLimitErrorResponseContent {
	message: string;
}
export interface Reaction {
	id: string;
	content: string;
	reacter: User;
	url: string;
}
export interface RedeemMagicLinkRequestContent {
	token: string;
}
export interface RedeemMagicLinkResponseContent {
	session_token: string;
	requires_signup_completion: boolean;
}
export interface RegisterDeviceRequestContent {
	token: string;
	platform: string;
	name?: string;
}
export interface RequestEmailAddressChangeRequestContent {
	email_address: string;
}
export interface RichTextBody {
	plain_text: string;
	html: string;
}
export interface SearchCardsResponseContent {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	column?: {
		id: string;
		name: string;
		color?: { name: string; value: string };
		created_at: string;
		cards_url?: string;
	};
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	assignees?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	}[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: { id: string; content: string; completed: boolean }[];
}
export interface SessionAuthorization {
	session_token: string;
	requires_signup_completion: boolean;
}
export interface Step {
	id: string;
	content: string;
	completed: boolean;
}
export interface StringMap {}
export interface Tag {
	id: string;
	title: string;
	created_at: string;
	url?: string;
}
export interface TagCardRequestContent {
	tag_title: string;
}
export interface TriageCardRequestContent {
	column_id?: string;
}
export interface UnauthorizedErrorResponseContent {
	message: string;
}
export interface UpdateAccountEntropyRequestContent {
	auto_postpone_period_in_days?: number;
}
export interface UpdateAccountEntropyResponseContent {
	id: string;
	name: string;
	cards_count: number;
	created_at: string;
	auto_postpone_period_in_days?: number;
}
export interface UpdateAccountSettingsRequestContent {
	name?: string;
}
export interface UpdateBoardEntropyRequestContent {
	auto_postpone_period_in_days?: number;
}
export interface UpdateBoardEntropyResponseContent {
	id: string;
	name: string;
	all_access: boolean;
	created_at: string;
	auto_postpone_period_in_days?: number;
	public_description?: string;
	public_description_html?: string;
	public_url?: string;
	user_ids?: string[];
	url: string;
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
}
export interface UpdateBoardInvolvementRequestContent {
	involvement?: string;
}
export interface UpdateBoardRequestContent {
	name?: string;
	all_access?: boolean;
	auto_postpone_period_in_days?: number;
	public_description?: string;
	user_ids?: string[];
}
export interface UpdateBoardResponseContent {
	id: string;
	name: string;
	all_access: boolean;
	created_at: string;
	auto_postpone_period_in_days?: number;
	public_description?: string;
	public_description_html?: string;
	public_url?: string;
	user_ids?: string[];
	url: string;
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
}
export interface UpdateCardRequestContent {
	title?: string;
	description?: string;
	column_id?: string;
	image?: string;
	created_at?: string;
}
export interface UpdateCardResponseContent {
	id: string;
	number: number;
	title: string;
	status: string;
	description?: string;
	description_html?: string;
	image_url?: string;
	has_attachments: boolean;
	tags?: string[];
	closed: boolean;
	postponed: boolean;
	golden: boolean;
	last_active_at?: string;
	created_at: string;
	url: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
	column?: {
		id: string;
		name: string;
		color?: { name: string; value: string };
		created_at: string;
		cards_url?: string;
	};
	creator?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	assignees?: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	}[];
	has_more_assignees?: boolean;
	comments_url?: string;
	reactions_url?: string;
	steps?: { id: string; content: string; completed: boolean }[];
}
export interface UpdateColumnRequestContent {
	name?: string;
	color?: string;
}
export interface UpdateColumnResponseContent {
	id: string;
	name: string;
	color?: { name: string; value: string };
	created_at: string;
	cards_url?: string;
}
export interface UpdateCommentRequestContent {
	body: string;
}
export interface UpdateCommentResponseContent {
	id: string;
	created_at: string;
	updated_at: string;
	body: { plain_text: string; html: string };
	creator: {
		id: string;
		name: string;
		role: string;
		active: boolean;
		email_address: string;
		created_at: string;
		url: string;
		avatar_url?: string;
	};
	card?: { id: string; url: string };
	reactions_url?: string;
	url: string;
}
export interface UpdateJoinCodeRequestContent {
	usage_limit?: number;
}
export interface UpdateMyTimezoneRequestContent {
	timezone_name: string;
}
export interface UpdateNotificationSettingsRequestContent {
	bundle_email_frequency?: string;
}
export interface UpdateStepRequestContent {
	content?: string;
	completed?: boolean;
}
export interface UpdateStepResponseContent {
	id: string;
	content: string;
	completed: boolean;
}
export interface UpdateUserRequestContent {
	name?: string;
}
export interface UpdateUserResponseContent {
	id: string;
	name: string;
	role: string;
	active: boolean;
	email_address: string;
	created_at: string;
	url: string;
	avatar_url?: string;
}
export interface UpdateUserRoleRequestContent {
	role: string;
}
export interface UpdateWebhookRequestContent {
	name?: string;
	url?: string;
	subscribed_actions?: string[];
}
export interface UpdateWebhookResponseContent {
	id: string;
	name: string;
	payload_url: string;
	url: string;
	subscribed_actions: string[];
	signing_secret: string;
	active: boolean;
	created_at: string;
	updated_at?: string;
	board?: {
		id: string;
		name: string;
		all_access: boolean;
		created_at: string;
		auto_postpone_period_in_days?: number;
		public_description?: string;
		public_description_html?: string;
		public_url?: string;
		user_ids?: string[];
		url: string;
		creator?: {
			id: string;
			name: string;
			role: string;
			active: boolean;
			email_address: string;
			created_at: string;
			url: string;
			avatar_url?: string;
		};
	};
}
export interface User {
	id: string;
	name: string;
	role: string;
	active: boolean;
	email_address: string;
	created_at: string;
	url: string;
	avatar_url?: string;
}
export interface ValidationErrorResponseContent {
	message: string;
	errors?: string[];
}
export interface Webhook {
	id: string;
	name: string;
	payload_url: string;
	url: string;
	subscribed_actions: string[];
	signing_secret: string;
	active: boolean;
	created_at: string;
	updated_at?: string;
	board?: Board;
}
export interface WebhookDelivery {
	id: string;
	state: string;
	created_at: string;
	updated_at: string;
	request?: WebhookDeliveryRequest;
	response?: WebhookDeliveryResponse;
	event?: WebhookDeliveryEvent;
}
export interface WebhookDeliveryEvent {
	id: string;
	action: string;
	created_at: string;
	creator?: WebhookDeliveryEventCreator;
	eventable?: WebhookDeliveryEventEventable;
}
export interface WebhookDeliveryEventCreator {
	id: string;
	name: string;
}
export interface WebhookDeliveryEventEventable {
	type: string;
	id: string;
	url: string;
}
export interface WebhookDeliveryRequest {
	headers?: StringMap;
}
export interface WebhookDeliveryResponse {
	code?: number;
	error?: string;
}
