import type { ParsedEndpoint, ParsedSpec, ParsedTypeDef } from "../domain/openapi-models";
import { toFnName, toPascalCase } from "../domain/codegen-utils";

const TS_IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

export const renderPropertyKey = (name: string): string =>
	TS_IDENTIFIER.test(name) ? name : JSON.stringify(name);

export const renderPropertyAccess = (objectName: string, propertyName: string): string =>
	TS_IDENTIFIER.test(propertyName)
		? `${objectName}.${propertyName}`
		: `${objectName}[${JSON.stringify(propertyName)}]`;

export function collectUsedTypeNames(spec: ParsedSpec): string[] {
	const refs = spec.endpoints.flatMap((endpoint) => [
		endpoint.bodyTypeRef,
		endpoint.responseTypeRef,
		...endpoint.pathParams.map((param) => param.typeRef),
		...endpoint.queryParams.map((param) => param.typeRef),
	]);
	return Object.keys(spec.types).filter((name) =>
		refs.some((ref) => ref && containsTypeName(ref, name)),
	);
}

const containsTypeName = (ref: string, name: string): boolean => {
	const escaped = name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
	return new RegExp(`(^|[^A-Za-z0-9_$])${escaped}($|[^A-Za-z0-9_$])`).test(ref);
};

export function generateTypes(spec: ParsedSpec): string {
	const lines: string[] = [];
	lines.push("// Generated by fizzyx. Do not edit.");
	lines.push("");

	for (const [name, typeDef] of Object.entries(spec.types)) {
		lines.push(renderTypeDef(name, typeDef));
	}

	return lines.join("\n");
}

function formatDescription(desc: string, indent: string): string {
	if (!desc) return "";
	const wrapped = desc
		.split("\n")
		.map((l) => `${indent} * ${l}`)
		.join("\n");
	return `\n${indent}/**\n${wrapped}\n${indent} */`;
}

function renderTypeDef(name: string, def: ParsedTypeDef): string {
	const header = def.description ? formatDescription(def.description, "") + "\n" : "";

	switch (def.kind) {
		case "interface": {
			const props = def.properties ?? [];
			const lines: string[] = [`${header}export interface ${name} {`];
			for (const prop of props) {
				const opt = prop.required ? "" : "?";
				if (prop.description) {
					lines.push(...formatDescription(prop.description, "  ").split("\n"));
				}
				lines.push(`  ${renderPropertyKey(prop.name)}${opt}: ${prop.tsType}`);
			}
			lines.push("}");
			return lines.join("\n");
		}
		case "enum": {
			const values = def.values ?? [];
			return `${header}export type ${name} = ${values.join(" | ")}`;
		}
		case "alias": {
			return `${header}export type ${name} = ${def.aliasType ?? "unknown"}`;
		}
	}
}

function convertPathToTemplate(
	path: string,
	paramNames: string[],
	useParamsPrefix = false,
): string {
	let result = path;
	for (const name of paramNames) {
		const access = useParamsPrefix ? renderPropertyAccess("params", name) : name;
		result = result.replace(`{${name}}`, `\${${access}}`);
	}
	return result;
}

export interface ApiImports {
	runtimeModule: string;
	typeExports: string[];
	valueExports: string[];
}

export function generateApi(
	spec: ParsedSpec,
	imports: ApiImports,
	typesImportPath: string | undefined,
	hasTypes: boolean,
): string {
	const lines: string[] = [];
	lines.push("// Generated by fizzyx. Do not edit.");
	lines.push("");
	lines.push(`import { request } from "${imports.runtimeModule}"`);
	if (imports.typeExports.length > 0) {
		lines.push(`export type { ${imports.typeExports.join(", ")} } from "${imports.runtimeModule}"`);
	}
	if (imports.valueExports.length > 0) {
		lines.push(`export { ${imports.valueExports.join(", ")} } from "${imports.runtimeModule}"`);
	}
	const usedTypeNames = collectUsedTypeNames(spec);
	if (hasTypes && typesImportPath && usedTypeNames.length > 0) {
		lines.push(`import type { ${usedTypeNames.join(", ")} } from "${typesImportPath}"`);
	}
	lines.push("");

	const needsBaseParams = spec.endpoints.some(
		(e) => e.pathParams.length > 0 || e.queryParams.length > 0,
	);
	if (needsBaseParams) {
		lines.push("export interface BaseParams {");
		lines.push("  [key: string]: unknown");
		lines.push("}");
		lines.push("");
	}

	for (const endpoint of spec.endpoints) {
		lines.push(renderEndpoint(endpoint));
	}

	return lines.join("\n");
}

export function renderEndpoint(endpoint: ParsedEndpoint): string {
	const { method, path, pathParams, queryParams, bodyTypeRef, responseTypeRef } = endpoint;

	const fnName = toFnName(endpoint);
	const typePrefix = toPascalCase(fnName);
	const useParamsPrefix = pathParams.length > 0;
	const tsPath = convertPathToTemplate(
		path,
		pathParams.map((p) => p.name),
		useParamsPrefix,
	);

	const hasBody = bodyTypeRef !== undefined;
	const hasPathParams = pathParams.length > 0;
	const hasQueryParams = queryParams.length > 0;

	const responseType = responseTypeRef ?? "void";

	const typeLines: string[] = [];
	const allParams: string[] = [];
	const jsdocLines: string[] = [];

	if (endpoint.description) {
		jsdocLines.push(endpoint.description);
	}

	if (hasPathParams) {
		const typeName = `${typePrefix}PathParams`;
		typeLines.push(`export interface ${typeName} extends BaseParams {`);
		for (const p of pathParams) {
			if (p.description) {
				typeLines.push(`  /** ${p.description} */`);
			}
			typeLines.push(`  ${renderPropertyKey(p.name)}: ${p.typeRef}`);
		}
		typeLines.push("}");
		allParams.push(`params: ${typeName}`);
		for (const p of pathParams) {
			if (p.description) {
				jsdocLines.push(`@param params.${p.name} - ${p.description}`);
			}
		}
	}

	if (hasBody && bodyTypeRef) {
		allParams.push(`data: ${bodyTypeRef}`);
		jsdocLines.push("@param data - Request body");
	}

	if (hasQueryParams) {
		const typeName = `${typePrefix}QueryParams`;
		typeLines.push(`export interface ${typeName} extends BaseParams {`);
		for (const q of queryParams) {
			if (q.description) {
				typeLines.push(`  /** ${q.description} */`);
			}
			typeLines.push(`  ${renderPropertyKey(q.name)}${q.required ? "" : "?"}: ${q.typeRef}`);
		}
		typeLines.push("}");
		allParams.push(`query?: ${typeName}`);
		for (const q of queryParams) {
			if (q.description) {
				jsdocLines.push(`@param query.${q.name} - ${q.description}`);
			}
		}
	}

	const callArgs: string[] = [];
	callArgs.push(JSON.stringify(method.toUpperCase()));
	callArgs.push(`\`${tsPath}\``);

	const optsParts: string[] = [];
	if (hasQueryParams) optsParts.push("query");
	if (hasBody) optsParts.push(`body: data`);

	const typeParams =
		hasBody && bodyTypeRef ? `<${responseType}, ${bodyTypeRef}>` : `<${responseType}>`;

	const callStr =
		optsParts.length > 0
			? `request${typeParams}(${callArgs.join(", ")}, { ${optsParts.join(", ")} })`
			: `request${typeParams}(${callArgs.join(", ")})`;

	const fnLines: string[] = [];

	if (jsdocLines.length > 0) {
		const desc = jsdocLines.join("\n * ");
		fnLines.push(`/**\n * ${desc}\n */`);
	}

	fnLines.push(`export function ${fnName}(${allParams.join(", ")}): Promise<${responseType}> {`);
	fnLines.push(`  return ${callStr}`);
	fnLines.push("}");

	const resultLines = typeLines.length > 0 ? [...typeLines, ...fnLines] : fnLines;
	return resultLines.join("\n");
}
