import { Effect } from "effect";
import { CodegenError } from "../domain/errors";
import type { CodeGenerator } from "../ports/code-generator";
import type {
	GenFileOptions,
	GeneratedFile,
	ParsedEndpoint,
	ParsedSpec,
	ParsedTypeDef,
} from "../domain/openapi-models";

const WX_RUNTIME_CODE = `// wx-request — lightweight wx.request client
// Generated by fizzyx. Only what you use ships.

export interface Logger {
  /** Log an error. */
  error: (...args: unknown[]) => void
  /** Log a warning. */
  warn: (...args: unknown[]) => void
  /** Log an info message. */
  info: (...args: unknown[]) => void
  /** Log a debug message. */
  debug: (...args: unknown[]) => void
}

/**
 * Custom token persistence. Default: wx.getStorageSync / setStorageSync
 * with key configurable via \`storageKey\`.
 */
export type TokenStorage = {
  get: () => string | null | Promise<string | null>
  set: (token: string | null) => void | Promise<void>
}

/** Context passed to every hook callback. */
export type HookContext = {
  method: string
  url: string
  status?: number
  duration: number
  message?: string
  body?: unknown
  data?: unknown
}

/**
 * Lifecycle hooks.
 * - \`onRequest\` fires before every request
 * - \`onSuccess\` fires on HTTP 2xx
 * - \`onError\` fires on HTTP 4xx/5xx or network failure
 */
export type RequestHook = {
  onRequest?: (ctx: HookContext) => void
  onSuccess?: (ctx: HookContext) => void
  onError?: (ctx: HookContext) => void
}

export type WxRequestConfig = {
  /** API base URL (prepended to relative paths). */
  baseUrl?: string
  /** Request timeout in ms (default 60000). */
  timeout?: number
  /** wx.getStorageSync key for token (default "fizzyx_token"). */
  storageKey?: string
  /** Custom token persistence. Replace to use wx Keychain / cloud sync. */
  tokenStorage?: TokenStorage
  /** Custom logger. Pass \`null\` fields to mute. */
  logger?: Logger
  /** Lifecycle hooks for toast, analytics, etc. */
  hooks?: RequestHook[]
  /**
   * Transform the raw response body before returning.
   * Default unwraps \`{ code, data }\` envelope → \`data\`.
   * Set to \`(raw) => raw\` to disable unwrapping.
   */
  responseExtractor?: (raw: unknown) => unknown
}

let _config: WxRequestConfig = {}
let _token: string | null = null
let _tokenStorage: TokenStorage | null = null
let _logger: Logger | null = null
let _hooks: RequestHook[] = []
let _extractor: ((raw: unknown) => unknown) | null = null

const defaultLogger: Logger = {
  error: (...args) => console.error("[fizzyx]", ...args),
  warn: (...args) => console.warn("[fizzyx]", ...args),
  info: (...args) => console.info("[fizzyx]", ...args),
  debug: (...args) => console.debug("[fizzyx]", ...args),
}

function getLogger(): Logger {
  return _logger ?? defaultLogger
}

function defaultExtractor(raw: unknown): unknown {
  if (raw !== null && typeof raw === "object" && "code" in (raw as Record<string, unknown>) && "data" in (raw as Record<string, unknown>)) {
    return (raw as Record<string, unknown>).data
  }
  return raw
}

function defaultTokenStorageKey(): string {
  return _config.storageKey ?? "fizzyx_token"
}

function defaultTokenStorage(): TokenStorage {
  const key = defaultTokenStorageKey()
  return {
    get: () => {
      try {
        const val = wx.getStorageSync<string | null>(key)
        return val ?? null
      } catch {
        return null
      }
    },
    set: (token) => {
      if (token) {
        wx.setStorageSync(key, token)
      } else {
        wx.removeStorageSync(key)
      }
    },
  }
}

async function loadInitialToken(): Promise<void> {
  const storage = _tokenStorage ?? defaultTokenStorage()
  try {
    const token = await storage.get()
    if (token !== null) _token = token
  } catch {
    // ignore storage errors at startup
  }
}

/**
 * Configure the client. Call once at app startup.
 *
 * \`\`\`ts
 * configure({ baseUrl: "https://api.example.com" })
 * configure({ storageKey: "myapp_token", logger: silentLogger })
 * \`\`\`
 */
export function configure(config: WxRequestConfig) {
  if (config.baseUrl !== undefined) _config.baseUrl = config.baseUrl
  if (config.timeout !== undefined) _config.timeout = config.timeout
  if (config.storageKey !== undefined) _config.storageKey = config.storageKey
  if (config.tokenStorage !== undefined) _tokenStorage = config.tokenStorage
  if (config.logger !== undefined) _logger = config.logger
  if (config.hooks !== undefined) _hooks = config.hooks
  if (config.responseExtractor !== undefined) _extractor = config.responseExtractor
  loadInitialToken()
}

/** (Re)load token from storage. Useful after login page redirect. */
export async function initToken(): Promise<void> {
  await loadInitialToken()
}

/**
 * Save token (memory + storage). Pass \`null\` to log out.
 * Auto-persists via tokenStorage. Default key: \`storageKey\`.
 */
export function setToken(token: string | null) {
  _token = token
  const storage = _tokenStorage ?? defaultTokenStorage()
  try {
    const result = storage.set(token)
    if (result instanceof Promise) {
      result.catch((e) => getLogger().error("failed to persist token:", e))
    }
  } catch (e) {
    getLogger().error("failed to persist token:", e)
  }
}

/** Register an error hook. Sugar for \`hooks.push({ onError })\`. */
export function onError(handler: ((ctx: HookContext) => void) | null) {
  if (handler) {
    _hooks = [..._hooks, { onError: handler }]
  }
}

function buildUrl(method: string, url: string, query?: Record<string, unknown>): string {
  let finalUrl = url.startsWith("http") ? url : (_config.baseUrl ?? "") + url
  if (query) {
    const parts: string[] = []
    for (const [key, val] of Object.entries(query)) {
      if (val !== undefined) {
        parts.push(encodeURIComponent(key) + "=" + encodeURIComponent(String(val)))
      }
    }
    if (parts.length > 0) finalUrl += "?" + parts.join("&")
  }
  return finalUrl
}

/**
 * Low-level request — returns the raw response body without transformation.
 *
 * Promise rejects on HTTP 4xx/5xx and network errors.
 * Errors also fire \`onError\` hooks — use those for toast / logging.
 */
export async function requestRaw<T>(
  method: string,
  url: string,
  options?: { query?: Record<string, unknown>; body?: unknown }
): Promise<T> {
  const log = getLogger()
  const start = Date.now()
  const finalUrl = buildUrl(method, url, options?.query)
  const header: Record<string, string> = {}
  if (_token) header["Authorization"] = \`Bearer \${_token}\`

  const hasHooks = _hooks.length > 0
  if (hasHooks) {
    const reqCtx: HookContext = { method, url: finalUrl, duration: 0, body: options?.body }
    for (const hook of _hooks) hook.onRequest?.(reqCtx)
  }

  return new Promise<T>((resolve, reject) => {
    wx.request({
      url: finalUrl,
      method: method as any,
      data: options?.body,
      timeout: _config.timeout ?? 60000,
      header,
      success: (res) => {
        const duration = Date.now() - start
        if (res.statusCode >= 400) {
          const errMsg = \`HTTP \${res.statusCode}\`
          log.error("request failed:", method, finalUrl, res.statusCode)
          if (hasHooks) {
            const ctx: HookContext = { method, url: finalUrl, status: res.statusCode, duration, message: errMsg }
            for (const hook of _hooks) hook.onError?.(ctx)
          }
          reject(new Error(errMsg))
          return
        }
        log.debug("request success:", method, finalUrl, res.statusCode)
        if (hasHooks) {
          const ctx: HookContext = { method, url: finalUrl, status: res.statusCode, duration, data: res.data as T }
          for (const hook of _hooks) hook.onSuccess?.(ctx)
        }
        resolve(res.data as T)
      },
      fail: (err) => {
        const duration = Date.now() - start
        log.error("request failed:", method, finalUrl, err.errMsg)
        if (hasHooks) {
          const ctx: HookContext = { method, url: finalUrl, duration, message: err.errMsg }
          for (const hook of _hooks) hook.onError?.(ctx)
        }
        reject(new Error(err.errMsg))
      },
    })
  })
}

/**
 * Typed request — applies \`responseExtractor\` to the raw response.
 * Default unwraps \`{ code, data }\` envelope → \`data\`.
 * Set \`responseExtractor: (raw) => raw\` in \`configure()\` to disable.
 */
export async function request<T>(
  method: string,
  url: string,
  options?: { query?: Record<string, unknown>; body?: unknown }
): Promise<T> {
  const raw = await requestRaw<unknown>(method, url, options)
  const extractor = _extractor ?? defaultExtractor
  return extractor(raw) as T
}
`;

const DEFAULT_WX_OPTIONS: GenFileOptions = {
	apiName: "api.ts",
	typesName: "types.ts",
	runtimeName: "wx-request.ts",
};

export const wxGenerator: CodeGenerator = {
	name: "wx",
	info: { name: "wx", description: "WeChat Mini Program (wx.request)" },

	generate: (spec: ParsedSpec, output: string, options?: GenFileOptions) =>
		Effect.gen(function* () {
			try {
				const opts = { ...DEFAULT_WX_OPTIONS, ...options };
				const files: GeneratedFile[] = [];

				const typesCode = generateTypes(spec);
				const hasTypes = spec.types && Object.keys(spec.types).length > 0;

				const typesFile = opts.typesName === false ? undefined : opts.typesName;
				const typesImportPath = typesFile ? `./${typesFile.replace(/\.ts$/, "")}` : undefined;

				const runtimeFile = opts.runtimeName;
				const runtimeImportPath = `./${runtimeFile.replace(/\.ts$/, "")}`;

				const apiCode = generateApi(spec, typesImportPath, hasTypes, runtimeImportPath);
				const apiImportPath = `./${opts.apiName.replace(/\.ts$/, "")}`;

				if (hasTypes && typesFile) {
					files.push({ path: typesFile, content: typesCode });
				}

				files.push({ path: runtimeFile, content: WX_RUNTIME_CODE });

				files.push({ path: opts.apiName, content: apiCode });

				files.push({
					path: "index.ts",
					content: [
						"// Generated by fizzyx. Do not edit.",
						"",
						`export * from "${apiImportPath}"`,
						...(typesImportPath && hasTypes ? [`export * from "${typesImportPath}"`] : []),
						"",
					].join("\n"),
				});

				return files;
			} catch (e) {
				return yield* Effect.fail(
					new CodegenError({
						message: `wx codegen failed: ${e instanceof Error ? e.message : String(e)}`,
						target: "wx",
						cause: e,
					}),
				);
			}
		}),
};

function generateTypes(spec: ParsedSpec): string {
	const lines: string[] = [];
	lines.push("// Generated by fizzyx. Do not edit.");
	lines.push("");

	for (const [name, typeDef] of Object.entries(spec.types)) {
		lines.push(renderTypeDef(name, typeDef));
	}

	return lines.join("\n");
}

function formatDescription(desc: string, indent: string): string {
	if (!desc) return "";
	const wrapped = desc
		.split("\n")
		.map((l) => `${indent} * ${l}`)
		.join("\n");
	return `\n${indent}/**\n${wrapped}\n${indent} */`;
}

function renderTypeDef(name: string, def: ParsedTypeDef): string {
	const header = def.description ? formatDescription(def.description, "") + "\n" : "";

	switch (def.kind) {
		case "interface": {
			const props = def.properties ?? [];
			const lines: string[] = [`${header}export interface ${name} {`];
			for (const prop of props) {
				const opt = prop.required ? "" : "?";
				if (prop.description) {
					lines.push(...formatDescription(prop.description, "  ").split("\n"));
				}
				lines.push(`  ${prop.name}${opt}: ${prop.tsType}`);
			}
			lines.push("}");
			return lines.join("\n");
		}
		case "enum": {
			const values = def.values ?? [];
			return `${header}export type ${name} = ${values.join(" | ")}`;
		}
		case "alias": {
			return `${header}export type ${name} = ${def.aliasType ?? "unknown"}`;
		}
	}
}

function generateApi(
	spec: ParsedSpec,
	typesImportPath: string | undefined,
	hasTypes: boolean,
	runtimeImportPath: string,
): string {
	const lines: string[] = [];
	lines.push("// Generated by fizzyx. Do not edit.");
	lines.push("");
	lines.push(`import { request } from "${runtimeImportPath}"`);
	lines.push(
		`export type { WxRequestConfig, Logger, TokenStorage, RequestHook, HookContext } from "${runtimeImportPath}"`,
	);
	lines.push(
		`export { configure, setToken, initToken, onError, requestRaw } from "${runtimeImportPath}"`,
	);
	if (hasTypes && typesImportPath) {
		lines.push(`import type { ${Object.keys(spec.types).join(", ")} } from "${typesImportPath}"`);
	}
	lines.push("");

	for (const endpoint of spec.endpoints) {
		lines.push(renderEndpoint(endpoint));
	}

	return lines.join("\n");
}

function toPascalCase(s: string): string {
	return s
		.replace(/[-_]/g, " ")
		.split(" ")
		.filter(Boolean)
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("");
}

function renderEndpoint(endpoint: ParsedEndpoint): string {
	const { method, path, operationId, pathParams, queryParams, bodyTypeRef, responseTypeRef } =
		endpoint;

	const fnName = operationId
		.split(".")
		.map((part, i) =>
			i === 0
				? part.replace(/-/g, "_")
				: part.charAt(0).toUpperCase() + part.slice(1).replace(/-/g, "_"),
		)
		.join("");
	const typePrefix = toPascalCase(fnName);
	const useParamsPrefix = pathParams.length > 0;
	const tsPath = convertPathToTemplate(
		path,
		pathParams.map((p) => p.name),
		useParamsPrefix,
	);

	const hasBody = bodyTypeRef !== undefined;
	const hasPathParams = pathParams.length > 0;
	const hasQueryParams = queryParams.length > 0;

	const responseType = responseTypeRef ?? "void";

	const typeLines: string[] = [];
	const allParams: string[] = [];
	const jsdocLines: string[] = [];

	// Endpoint description
	if (endpoint.description) {
		jsdocLines.push(endpoint.description);
	}

	if (hasPathParams) {
		const typeName = `${typePrefix}PathParams`;
		typeLines.push(`export interface ${typeName} {`);
		typeLines.push("  [key: string]: unknown");
		for (const p of pathParams) {
			if (p.description) {
				typeLines.push(`  /** ${p.description} */`);
			}
			typeLines.push(`  ${p.name}: ${p.typeRef}`);
		}
		typeLines.push("}");
		allParams.push(`params: ${typeName}`);
		for (const p of pathParams) {
			if (p.description) {
				jsdocLines.push(`@param params.${p.name} - ${p.description}`);
			}
		}
	}

	if (hasBody && bodyTypeRef) {
		allParams.push(`data: ${bodyTypeRef}`);
		jsdocLines.push("@param data - Request body");
	}

	if (hasQueryParams) {
		const typeName = `${typePrefix}QueryParams`;
		typeLines.push(`export interface ${typeName} {`);
		typeLines.push("  [key: string]: unknown");
		for (const q of queryParams) {
			if (q.description) {
				typeLines.push(`  /** ${q.description} */`);
			}
			typeLines.push(`  ${q.name}${q.required ? "" : "?"}: ${q.typeRef}`);
		}
		typeLines.push("}");
		allParams.push(`query?: ${typeName}`);
		for (const q of queryParams) {
			if (q.description) {
				jsdocLines.push(`@param query.${q.name} - ${q.description}`);
			}
		}
	}

	const callArgs: string[] = [];
	callArgs.push(JSON.stringify(method.toUpperCase()));
	callArgs.push(`\`${tsPath}\``);

	const optsParts: string[] = [];
	if (hasQueryParams) optsParts.push("query");
	if (hasBody) optsParts.push(`body: data`);

	const callStr =
		optsParts.length > 0
			? `request<${responseType}>(${callArgs.join(", ")}, { ${optsParts.join(", ")} })`
			: `request<${responseType}>(${callArgs.join(", ")})`;

	const fnLines: string[] = [];

	// Render JSDoc
	if (jsdocLines.length > 0) {
		const desc = jsdocLines.join("\n * ");
		fnLines.push(`/**\n * ${desc}\n */`);
	}

	fnLines.push(`export function ${fnName}(${allParams.join(", ")}): Promise<${responseType}> {`);
	fnLines.push(`  return ${callStr}`);
	fnLines.push("}");

	const resultLines = typeLines.length > 0 ? [...typeLines, ...fnLines] : fnLines;
	return resultLines.join("\n");
}

function convertPathToTemplate(
	path: string,
	paramNames: string[],
	useParamsPrefix = false,
): string {
	let result = path;
	for (const name of paramNames) {
		const prefix = useParamsPrefix ? `params.` : "";
		result = result.replace(`{${name}}`, `\${${prefix}${name}}`);
	}
	return result;
}
