import { Effect } from "effect";
import { CodegenError } from "../domain/errors";
import type { CodeGenerator } from "../ports/code-generator";
import type { GenFileOptions, GeneratedFile, ParsedSpec } from "../domain/openapi-models";
import { generateTypes, generateApi } from "./codegen-shared";

const WX_RUNTIME_CODE = `// wx-request — lightweight wx.request client
// Generated by fizzyx. Only what you use ships.

export interface Logger {
  /** Log an error. */
  error: (...args: unknown[]) => void
  /** Log a warning. */
  warn: (...args: unknown[]) => void
  /** Log an info message. */
  info: (...args: unknown[]) => void
  /** Log a debug message. */
  debug: (...args: unknown[]) => void
}

/**
 * Custom token persistence. Default: wx.getStorageSync / setStorageSync
 * with key configurable via \`storageKey\`.
 */
export type TokenStorage = {
  get: () => string | null | Promise<string | null>
  set: (token: string | null) => void | Promise<void>
}

/** Context passed to every hook callback. */
export type HookContext = {
  method: string
  url: string
  status?: number
  duration: number
  message?: string
  body?: unknown
  data?: unknown
}

/**
 * Lifecycle hooks.
 * - \`onRequest\` fires before every request
 * - \`onSuccess\` fires on HTTP 2xx
 * - \`onError\` fires on HTTP 4xx/5xx or network failure
 */
export type RequestHook = {
  onRequest?: (ctx: HookContext) => void
  onSuccess?: (ctx: HookContext) => void
  onError?: (ctx: HookContext) => void
}

export type WxRequestConfig = {
  /** API base URL (prepended to relative paths). */
  baseUrl?: string
  /** Default headers sent with every request. */
  headers?: Record<string, string>
  /** Request timeout in ms (default 60000). */
  timeout?: number
  /** wx.getStorageSync key for token (default "fizzyx_token"). */
  storageKey?: string
  /** Custom token persistence. Replace to use wx Keychain / cloud sync. */
  tokenStorage?: TokenStorage
  /** Custom logger. Pass \`null\` fields to mute. */
  logger?: Logger
  /** Lifecycle hooks for toast, analytics, etc. */
  hooks?: RequestHook[]
  /**
   * Transform the raw response body before returning.
   * Default unwraps \`{ code, data }\` envelope → \`data\`.
   * Set to \`(raw) => raw\` to disable unwrapping.
   */
  responseExtractor?: (raw: unknown) => unknown
}

let _config: WxRequestConfig = {}
let _token: string | null = null
let _tokenStorage: TokenStorage | null = null
let _logger: Logger | null = null
let _hooks: RequestHook[] = []
let _extractor: ((raw: unknown) => unknown) | null = null
let _defaultHeaders: Record<string, string> = {}

const defaultLogger: Logger = {
  error: (...args) => console.error("[fizzyx]", ...args),
  warn: (...args) => console.warn("[fizzyx]", ...args),
  info: (...args) => console.info("[fizzyx]", ...args),
  debug: (...args) => console.debug("[fizzyx]", ...args),
}

function getLogger(): Logger {
  return _logger ?? defaultLogger
}

function defaultExtractor(raw: unknown): unknown {
  if (raw !== null && typeof raw === "object" && "code" in (raw as Record<string, unknown>) && "data" in (raw as Record<string, unknown>)) {
    return (raw as Record<string, unknown>).data
  }
  return raw
}

function defaultTokenStorageKey(): string {
  return _config.storageKey ?? "fizzyx_token"
}

function defaultTokenStorage(): TokenStorage {
  const key = defaultTokenStorageKey()
  return {
    get: () => {
      try {
        const val = wx.getStorageSync<string | null>(key)
        return val ?? null
      } catch {
        return null
      }
    },
    set: (token) => {
      if (token) {
        wx.setStorageSync(key, token)
      } else {
        wx.removeStorageSync(key)
      }
    },
  }
}

async function loadInitialToken(): Promise<void> {
  const storage = _tokenStorage ?? defaultTokenStorage()
  try {
    const token = await storage.get()
    if (token !== null) _token = token
  } catch {
    // ignore storage errors at startup
  }
}

/**
 * Configure the client. Call once at app startup.
 *
 * \`\`\`ts
 * configure({ baseUrl: "https://api.example.com" })
 * configure({ storageKey: "myapp_token", logger: silentLogger })
 * \`\`\`
 */
export function configure(config: WxRequestConfig) {
  if (config.baseUrl !== undefined) _config.baseUrl = config.baseUrl
  if (config.timeout !== undefined) _config.timeout = config.timeout
  if (config.storageKey !== undefined) _config.storageKey = config.storageKey
  if (config.tokenStorage !== undefined) _tokenStorage = config.tokenStorage
  if (config.logger !== undefined) _logger = config.logger
  if (config.hooks !== undefined) _hooks = config.hooks
  if (config.responseExtractor !== undefined) _extractor = config.responseExtractor
  if (config.headers !== undefined) _defaultHeaders = config.headers
  loadInitialToken()
}

/** (Re)load token from storage. Useful after login page redirect. */
export async function initToken(): Promise<void> {
  await loadInitialToken()
}

/**
 * Save token (memory + storage). Pass \`null\` to log out.
 * Auto-persists via tokenStorage. Default key: \`storageKey\`.
 */
export function setToken(token: string | null) {
  _token = token
  const storage = _tokenStorage ?? defaultTokenStorage()
  try {
    const result = storage.set(token)
    if (result instanceof Promise) {
      result.catch((e) => getLogger().error("failed to persist token:", e))
    }
  } catch (e) {
    getLogger().error("failed to persist token:", e)
  }
}

/** Register an error hook. Sugar for \`hooks.push({ onError })\`. */
export function onError(handler: ((ctx: HookContext) => void) | null) {
  if (handler) {
    _hooks = [..._hooks, { onError: handler }]
  }
}

/** Set default headers sent with every request. Merge with existing defaults. */
export function setHeaders(headers: Record<string, string>): void {
  _defaultHeaders = { ..._defaultHeaders, ...headers }
}

function buildUrl(method: string, url: string, query?: Record<string, unknown>): string {
  let finalUrl = url.startsWith("http") ? url : (_config.baseUrl ?? "") + url
  if (query) {
    const parts: string[] = []
    for (const [key, val] of Object.entries(query)) {
      if (val !== undefined) {
        parts.push(encodeURIComponent(key) + "=" + encodeURIComponent(String(val)))
      }
    }
    if (parts.length > 0) finalUrl += "?" + parts.join("&")
  }
  return finalUrl
}

type HttpMethod = "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS";

/**
 * Low-level request — returns the raw response body without transformation.
 *
 * Promise rejects on HTTP 4xx/5xx and network errors.
 * Errors also fire \`onError\` hooks — use those for toast / logging.
 */
export async function requestRaw<T>(
  method: HttpMethod,
  url: string,
  options?: { query?: Record<string, unknown>; body?: unknown }
): Promise<T> {
  const log = getLogger()
  const start = Date.now()
  const finalUrl = buildUrl(method, url, options?.query)
  const header: Record<string, string> = { ..._defaultHeaders }
  if (_token) header["Authorization"] = \`Bearer \${_token}\`

  const hasHooks = _hooks.length > 0
  if (hasHooks) {
    const reqCtx: HookContext = { method, url: finalUrl, duration: 0, body: options?.body }
    for (const hook of _hooks) hook.onRequest?.(reqCtx)
  }

  return new Promise<T>((resolve, reject) => {
    wx.request({
      url: finalUrl,
      method: method as Parameters<typeof wx.request>[0]["method"],
      data: options?.body as Record<string, unknown>,
      timeout: _config.timeout ?? 60000,
      header,
      success: (res) => {
        const duration = Date.now() - start
        if (res.statusCode >= 400) {
          const errMsg = \`HTTP \${res.statusCode}\`
          log.error("request failed:", method, finalUrl, res.statusCode)
          if (hasHooks) {
            const ctx: HookContext = { method, url: finalUrl, status: res.statusCode, duration, message: errMsg }
            for (const hook of _hooks) hook.onError?.(ctx)
          }
          reject(new Error(errMsg))
          return
        }
        log.debug("request success:", method, finalUrl, res.statusCode)
        if (hasHooks) {
          const ctx: HookContext = { method, url: finalUrl, status: res.statusCode, duration, data: res.data as T }
          for (const hook of _hooks) hook.onSuccess?.(ctx)
        }
        resolve(res.data as T)
      },
      fail: (err) => {
        const duration = Date.now() - start
        log.error("request failed:", method, finalUrl, err.errMsg)
        if (hasHooks) {
          const ctx: HookContext = { method, url: finalUrl, duration, message: err.errMsg }
          for (const hook of _hooks) hook.onError?.(ctx)
        }
        reject(new Error(err.errMsg))
      },
    })
  })
}

/**
 * Typed request — applies \`responseExtractor\` to the raw response.
 * Default unwraps \`{ code, data }\` envelope → \`data\`.
 * Set \`responseExtractor: (raw) => raw\` in \`configure()\` to disable.
 */
export async function request<T, B = unknown>(
  method: HttpMethod,
  url: string,
  options?: { query?: Record<string, unknown>; body?: B }
): Promise<T> {
  const raw = await requestRaw<unknown>(method, url, options)
  const extractor = _extractor ?? defaultExtractor
  return extractor(raw) as T
}
`;

const DEFAULT_WX_OPTIONS: GenFileOptions = {
	apiName: "api.ts",
	typesName: "types.ts",
	runtimeName: "wx-request.ts",
};

export const wxGenerator: CodeGenerator = {
	name: "wx",
	info: { name: "wx", description: "WeChat Mini Program (wx.request)" },

	generate: (spec: ParsedSpec, output: string, options?: GenFileOptions) =>
		Effect.gen(function* () {
			try {
				const opts = {
					apiName: options?.apiName ?? DEFAULT_WX_OPTIONS.apiName,
					typesName: options?.typesName ?? DEFAULT_WX_OPTIONS.typesName,
					runtimeName: options?.runtimeName ?? DEFAULT_WX_OPTIONS.runtimeName,
				} as Required<GenFileOptions>;
				const files: GeneratedFile[] = [];

				const typesCode = generateTypes(spec);
				const hasTypes = spec.types && Object.keys(spec.types).length > 0;

				const typesFile = opts.typesName === false ? undefined : opts.typesName;
				const typesImportPath = typesFile ? `./${typesFile.replace(/\.ts$/, "")}` : undefined;

				const runtimeFile = opts.runtimeName;
				const runtimeImportPath = `./${runtimeFile.replace(/\.ts$/, "")}`;

				const apiCode = generateApi(
					spec,
					{
						runtimeModule: runtimeImportPath,
						typeExports: [
							"WxRequestConfig",
							"Logger",
							"TokenStorage",
							"RequestHook",
							"HookContext",
						],
						valueExports: [
							"configure",
							"setToken",
							"setHeaders",
							"initToken",
							"onError",
							"requestRaw",
						],
					},
					typesImportPath,
					hasTypes,
				);
				const apiImportPath = `./${opts.apiName.replace(/\.ts$/, "")}`;

				if (hasTypes && typesFile) {
					files.push({ path: typesFile, content: typesCode });
				}

				files.push({ path: runtimeFile, content: WX_RUNTIME_CODE });

				files.push({ path: opts.apiName, content: apiCode });

				files.push({
					path: "index.ts",
					content: [
						"// Generated by fizzyx. Do not edit.",
						"",
						`export * from "${apiImportPath}"`,
						...(typesImportPath && hasTypes ? [`export * from "${typesImportPath}"`] : []),
						"",
					].join("\n"),
				});

				return files;
			} catch (e) {
				return yield* Effect.fail(
					new CodegenError({
						message: `wx codegen failed: ${e instanceof Error ? e.message : String(e)}`,
						target: "wx",
						cause: e,
					}),
				);
			}
		}),
};
