import { Effect } from "effect";
import { CodegenError } from "../domain/errors";
import type { CodeGenerator } from "../ports/code-generator";
import type { GenFileOptions, GeneratedFile, ParsedSpec } from "../domain/openapi-models";
import { generateTypes, generateApi } from "./codegen-shared";

const WX_RUNTIME_CODE = `// wx-request — lightweight wx.request client
// Generated by fizzyx. Keep API surface small, keep behavior explicit.

export interface Logger {
  /** Log an error. */
  error: (...args: unknown[]) => void
  /** Log a warning. */
  warn: (...args: unknown[]) => void
  /** Log an info message. */
  info: (...args: unknown[]) => void
  /** Log a debug message. */
  debug: (...args: unknown[]) => void
}

/**
 * Custom token persistence.
 * Default uses wx.getStorageSync / wx.setStorageSync with configurable key.
 */
export interface TokenStorage {
  get: () => string | null | Promise<string | null>
  set: (token: string | null) => void | Promise<void>
}

/** Context passed to every hook callback. */
export interface HookContext {
  method: string
  url: string
  status?: number
  duration: number
  message?: string
  body?: unknown
  data?: unknown
}

/**
 * Lifecycle hooks:
 * - onRequest: before request is sent
 * - onSuccess: HTTP 2xx responses
 * - onError: HTTP 4xx/5xx or network failures
 */
export interface RequestHook {
  onRequest?: (ctx: HookContext) => void
  onSuccess?: (ctx: HookContext) => void
  onError?: (ctx: HookContext) => void
}

export interface WxRequestConfig {
  /** API base URL (prepended to relative paths). */
  baseUrl?: string
  /** Default headers sent with every request. */
  headers?: Record<string, string>
  /** Request timeout in ms (default 60000). */
  timeout?: number
  /** wx.getStorageSync key for token (default "fizzyx_token"). */
  storageKey?: string
  /** Custom token persistence. Replace to use Keychain / cloud sync. */
  tokenStorage?: TokenStorage
  /** Custom logger. */
  logger?: Logger
  /** Lifecycle hooks. */
  hooks?: RequestHook[]
  /**
   * Transform the raw response body before returning.
   * Default unwraps { code, data } envelope -> data.
   * Set to (raw) => raw to disable.
   */
  responseExtractor?: (raw: unknown) => unknown
}

export interface RequestOptions<B = unknown> {
  query?: Record<string, unknown>
  body?: B
  headers?: Record<string, string>
}

type HttpMethod = "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS"

const DEFAULT_TIMEOUT_MS = 60000
const DEFAULT_TOKEN_KEY = "fizzyx_token"

let _config: WxRequestConfig = {}
let _token: string | null = null
let _tokenStorage: TokenStorage | null = null
let _logger: Logger | null = null
let _hooks: RequestHook[] = []
let _extractor: ((raw: unknown) => unknown) | null = null
let _defaultHeaders: Record<string, string> = {}

const defaultLogger: Logger = {
  error: (...args) => console.error("[fizzyx]", ...args),
  warn: (...args) => console.warn("[fizzyx]", ...args),
  info: (...args) => console.info("[fizzyx]", ...args),
  debug: (...args) => console.debug("[fizzyx]", ...args),
}

function getLogger(): Logger {
  return _logger ?? defaultLogger
}

function defaultExtractor(raw: unknown): unknown {
  if (raw !== null && typeof raw === "object" && "code" in (raw as Record<string, unknown>) && "data" in (raw as Record<string, unknown>)) {
    return (raw as Record<string, unknown>).data
  }
  return raw
}

function defaultTokenStorageKey(): string {
  return _config.storageKey ?? DEFAULT_TOKEN_KEY
}

function defaultTokenStorage(): TokenStorage {
  const key = defaultTokenStorageKey()
  return {
    get: () => {
      try {
        const val = wx.getStorageSync<string | null>(key)
        return val ?? null
      } catch {
        return null
      }
    },
    set: (token) => {
      if (token) {
        wx.setStorageSync(key, token)
      } else {
        wx.removeStorageSync(key)
      }
    },
  }
}

async function loadInitialToken(): Promise<void> {
  const storage = _tokenStorage ?? defaultTokenStorage()
  try {
    const token = await storage.get()
    if (token !== null) _token = token
  } catch {
    // ignore storage errors at startup
  }
}

function callOnRequest(ctx: HookContext): void {
  for (const hook of _hooks) {
    hook.onRequest?.(ctx)
  }
}

function callOnSuccess(ctx: HookContext): void {
  for (const hook of _hooks) {
    hook.onSuccess?.(ctx)
  }
}

function callOnError(ctx: HookContext): void {
  for (const hook of _hooks) {
    hook.onError?.(ctx)
  }
}

function queryValueToString(value: unknown): string {
  if (value === null || value === undefined) return ""
  if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") {
    return String(value)
  }
  return JSON.stringify(value)
}

function buildQueryString(query?: Record<string, unknown>): string {
  if (!query) return ""

  const parts: string[] = []
  for (const [key, val] of Object.entries(query)) {
    if (val === undefined) continue
    if (Array.isArray(val)) {
      for (const item of val) {
        if (item === undefined) continue
        parts.push(encodeURIComponent(key) + "=" + encodeURIComponent(queryValueToString(item)))
      }
      continue
    }
    parts.push(encodeURIComponent(key) + "=" + encodeURIComponent(queryValueToString(val)))
  }

  if (parts.length === 0) return ""
  return "?" + parts.join("&")
}

function buildUrl(url: string, query?: Record<string, unknown>): string {
  const finalBase = url.startsWith("http") ? "" : (_config.baseUrl ?? "")
  return finalBase + url + buildQueryString(query)
}

function buildHeaders(optionsHeaders?: Record<string, string>): Record<string, string> {
  const header: Record<string, string> = { ..._defaultHeaders, ...(optionsHeaders ?? {}) }
  if (_token) header.Authorization = "Bearer " + _token
  return header
}

function hasHooks(): boolean {
  return _hooks.length > 0
}

/**
 * Configure the client. Call once at app startup.
 */
export function configure(config: WxRequestConfig) {
  if (config.baseUrl !== undefined) _config.baseUrl = config.baseUrl
  if (config.timeout !== undefined) _config.timeout = config.timeout
  if (config.storageKey !== undefined) _config.storageKey = config.storageKey
  if (config.tokenStorage !== undefined) _tokenStorage = config.tokenStorage
  if (config.logger !== undefined) _logger = config.logger
  if (config.hooks !== undefined) _hooks = config.hooks
  if (config.responseExtractor !== undefined) _extractor = config.responseExtractor
  if (config.headers !== undefined) _defaultHeaders = config.headers
  void loadInitialToken()
}

/** (Re)load token from storage. Useful after login page redirect. */
export async function initToken(): Promise<void> {
  await loadInitialToken()
}

/**
 * Save token (memory + storage). Pass null to log out.
 * Auto-persists via tokenStorage. Default key: storageKey.
 */
export function setToken(token: string | null): void {
  _token = token
  const storage = _tokenStorage ?? defaultTokenStorage()
  try {
    const result = storage.set(token)
    if (result instanceof Promise) {
      result.catch((e) => getLogger().error("failed to persist token:", e))
    }
  } catch (e) {
    getLogger().error("failed to persist token:", e)
  }
}

/** Register an error hook. Sugar for hooks.push({ onError }). */
export function onError(handler: ((ctx: HookContext) => void) | null) {
  if (handler) {
    _hooks = [..._hooks, { onError: handler }]
  }
}

/** Set default headers sent with every request. Merge with existing defaults. */
export function setHeaders(headers: Record<string, string>): void {
  _defaultHeaders = { ..._defaultHeaders, ...headers }
}

/**
 * Low-level request — returns the raw response body without transformation.
 *
 * Promise rejects on HTTP 4xx/5xx and network errors.
 * Errors also fire onError hooks — use those for toast / logging.
 */
export async function requestRaw<T>(
  method: HttpMethod,
  url: string,
  options: RequestOptions<unknown> = {},
): Promise<T> {
  const log = getLogger()
  const start = Date.now()
  const finalUrl = buildUrl(url, options.query)
  const header = buildHeaders(options.headers)
  const shouldRunHooks = hasHooks()

  if (shouldRunHooks) {
    callOnRequest({ method, url: finalUrl, duration: 0, body: options.body })
  }

  return new Promise<T>((resolve, reject) => {
    wx.request({
      url: finalUrl,
      method: method as NonNullable<WechatMiniprogram.RequestOption["method"]>,
      data: options.body as Record<string, unknown>,
      timeout: _config.timeout ?? DEFAULT_TIMEOUT_MS,
      header,
      success: (res) => {
        const duration = Date.now() - start
        if (res.statusCode >= 400) {
          const errMsg = "HTTP " + res.statusCode
          log.error("request failed:", method, finalUrl, res.statusCode)
          if (shouldRunHooks) {
            callOnError({ method, url: finalUrl, status: res.statusCode, duration, message: errMsg })
          }
          reject(new Error(errMsg))
          return
        }
        log.debug("request success:", method, finalUrl, res.statusCode)
        if (shouldRunHooks) {
          callOnSuccess({ method, url: finalUrl, status: res.statusCode, duration, data: res.data as T })
        }
        resolve(res.data as T)
      },
      fail: (err) => {
        const duration = Date.now() - start
        log.error("request failed:", method, finalUrl, err.errMsg)
        if (shouldRunHooks) {
          callOnError({ method, url: finalUrl, duration, message: err.errMsg })
        }
        reject(new Error(err.errMsg))
      },
    })
  })
}

/**
 * Typed request — applies responseExtractor to the raw response.
 * Default unwraps { code, data } envelope -> data.
 * Set responseExtractor: (raw) => raw in configure() to disable.
 */
export async function request<T, B = unknown>(
  method: HttpMethod,
  url: string,
  options?: RequestOptions<B>,
): Promise<T> {
  const raw = await requestRaw<unknown>(method, url, options)
  const extractor = _extractor ?? defaultExtractor
  return extractor(raw) as T
}

// --- File upload / download (wx.uploadFile / wx.downloadFile) ---

export interface UploadFileOptions {
  filePath: string
  fileName: string
  query?: Record<string, unknown>
  formData?: Record<string, unknown>
  header?: Record<string, string>
}

/**
 * Low-level file upload — returns raw response body without transformation.
 * Uses wx.uploadFile under the hood.
 */
export async function uploadFileRaw<T>(
  url: string,
  options: UploadFileOptions,
): Promise<T> {
  const log = getLogger()
  const start = Date.now()
  const finalUrl = buildUrl(url, options.query)
  const header = buildHeaders(options.header)
  const shouldRunHooks = hasHooks()

  if (shouldRunHooks) {
    callOnRequest({ method: "POST", url: finalUrl, duration: 0 })
  }

  return new Promise<T>((resolve, reject) => {
    wx.uploadFile({
      url: finalUrl,
      filePath: options.filePath,
      name: options.fileName,
      header,
      formData: options.formData as Record<string, unknown>,
      timeout: _config.timeout ?? DEFAULT_TIMEOUT_MS,
      success: (res) => {
        const duration = Date.now() - start
        if (res.statusCode >= 400) {
          const errMsg = "HTTP " + res.statusCode
          log.error("upload failed:", finalUrl, res.statusCode)
          if (shouldRunHooks) {
            callOnError({ method: "POST", url: finalUrl, status: res.statusCode, duration, message: errMsg })
          }
          reject(new Error(errMsg))
          return
        }
        log.debug("upload success:", finalUrl, res.statusCode)
        let data: unknown = res.data
        try { data = JSON.parse(res.data as string) } catch { /* keep raw string */ }
        if (shouldRunHooks) {
          callOnSuccess({ method: "POST", url: finalUrl, status: res.statusCode, duration, data })
        }
        resolve(data as T)
      },
      fail: (err) => {
        const duration = Date.now() - start
        log.error("upload failed:", finalUrl, err.errMsg)
        if (shouldRunHooks) {
          callOnError({ method: "POST", url: finalUrl, duration, message: err.errMsg })
        }
        reject(new Error(err.errMsg))
      },
    })
  })
}

/**
 * Typed file upload — applies responseExtractor to the raw response.
 */
export async function uploadFile<T>(
  url: string,
  options: UploadFileOptions,
): Promise<T> {
  const raw = await uploadFileRaw<unknown>(url, options)
  const extractor = _extractor ?? defaultExtractor
  return extractor(raw) as T
}

/**
 * Download a file via wx.downloadFile.
 * Resolves with the temporary file path (tempFilePath).
 */
export async function downloadFile(
  url: string,
  options?: { query?: Record<string, unknown>; header?: Record<string, string> },
): Promise<string> {
  const log = getLogger()
  const start = Date.now()
  const finalUrl = buildUrl(url, options?.query)
  const header = buildHeaders(options?.header)
  const shouldRunHooks = hasHooks()

  if (shouldRunHooks) {
    callOnRequest({ method: "GET", url: finalUrl, duration: 0 })
  }

  return new Promise<string>((resolve, reject) => {
    wx.downloadFile({
      url: finalUrl,
      header,
      timeout: _config.timeout ?? DEFAULT_TIMEOUT_MS,
      success: (res) => {
        const duration = Date.now() - start
        if (res.statusCode >= 400) {
          const errMsg = "HTTP " + res.statusCode
          log.error("download failed:", finalUrl, res.statusCode)
          if (shouldRunHooks) {
            callOnError({ method: "GET", url: finalUrl, status: res.statusCode, duration, message: errMsg })
          }
          reject(new Error(errMsg))
          return
        }
        log.debug("download success:", finalUrl, res.statusCode, res.tempFilePath)
        if (shouldRunHooks) {
          callOnSuccess({ method: "GET", url: finalUrl, status: res.statusCode, duration, data: res.tempFilePath })
        }
        resolve(res.tempFilePath)
      },
      fail: (err) => {
        const duration = Date.now() - start
        log.error("download failed:", finalUrl, err.errMsg)
        if (shouldRunHooks) {
          callOnError({ method: "GET", url: finalUrl, duration, message: err.errMsg })
        }
        reject(new Error(err.errMsg))
      },
    })
  })
}
`;

const DEFAULT_WX_OPTIONS: GenFileOptions = {
	apiName: "api.ts",
	typesName: "types.ts",
	runtimeName: "wx-request.ts",
};

export const wxGenerator: CodeGenerator = {
	name: "wx",
	info: {
		name: "wx",
		description: "WeChat Mini Program (wx.request / wx.uploadFile / wx.downloadFile)",
	},

	generate: (spec: ParsedSpec, output: string, options?: GenFileOptions) =>
		Effect.gen(function* () {
			try {
				const opts = {
					apiName: options?.apiName ?? DEFAULT_WX_OPTIONS.apiName,
					typesName: options?.typesName ?? DEFAULT_WX_OPTIONS.typesName,
					runtimeName: options?.runtimeName ?? DEFAULT_WX_OPTIONS.runtimeName,
				} as Required<GenFileOptions>;
				const files: GeneratedFile[] = [];

				const typesCode = generateTypes(spec);
				const hasTypes = spec.types && Object.keys(spec.types).length > 0;

				const typesFile = opts.typesName === false ? undefined : opts.typesName;
				const typesImportPath = typesFile ? `./${typesFile.replace(/\.ts$/, "")}` : undefined;

				const runtimeFile = opts.runtimeName;
				const runtimeImportPath = `./${runtimeFile.replace(/\.ts$/, "")}`;

				const hasUpload = spec.endpoints.some((e) => e.bodyContentType === "multipart");
				const hasDownload = spec.endpoints.some((e) => e.responseContentType === "binary");
				const valueExports: string[] = [
					"configure",
					"setToken",
					"setHeaders",
					"initToken",
					"onError",
					"requestRaw",
				];
				if (hasUpload) valueExports.push("uploadFile", "uploadFileRaw");
				if (hasDownload) valueExports.push("downloadFile");

				const apiCode = generateApi(
					spec,
					{
						runtimeModule: runtimeImportPath,
						typeExports: [
							"WxRequestConfig",
							"Logger",
							"TokenStorage",
							"RequestHook",
							"HookContext",
						],
						valueExports,
						runtimeUploadImport: hasUpload ? "uploadFile" : undefined,
						runtimeDownloadImport: hasDownload ? "downloadFile" : undefined,
					},
					typesImportPath,
					hasTypes,
				);

				if (hasTypes && typesFile) {
					files.push({ path: typesFile, content: typesCode });
				}

				files.push({ path: runtimeFile, content: WX_RUNTIME_CODE });

				files.push({ path: opts.apiName, content: apiCode });

				return files;
			} catch (e) {
				return yield* Effect.fail(
					new CodegenError({
						message: `wx codegen failed: ${e instanceof Error ? e.message : String(e)}`,
						target: "wx",
						cause: e,
					}),
				);
			}
		}),
};
