import { Effect } from "effect";
import type { CodeGenerator } from "../ports/code-generator";
import type { ParsedEndpoint, ParsedSpec } from "../domain/openapi-models";
import { toFnName, toPascalCase } from "../domain/codegen-utils";
import { CodegenError } from "../domain/errors";

export const tanstackQueryGenerator: CodeGenerator = {
	name: "tanstack-query",
	info: { name: "tanstack-query", description: "TanStack Query React hooks" },

	generate: (spec: ParsedSpec, _output: string, options) =>
		Effect.gen(function* () {
			try {
				const defaultName =
					options?.typesName !== false ? (options?.typesName ?? "types.ts") : undefined;
				const apiImportPath = `./${options?.apiName?.replace(/\.ts$/, "") ?? "api"}`;
				const typesImportPath = defaultName ? `./${defaultName.replace(/\.ts$/, "")}` : undefined;
				const hasTypes =
					defaultName !== undefined && spec.types && Object.keys(spec.types).length > 0;

				return [
					{
						path: "queries.ts",
						content: generateTanstackQueryCode(spec, apiImportPath, typesImportPath, hasTypes),
					},
				];
			} catch (e) {
				return yield* Effect.fail(
					new CodegenError({
						message: `tanstack-query codegen failed: ${e instanceof Error ? e.message : String(e)}`,
						target: "tanstack-query",
						cause: e,
					}),
				);
			}
		}),
};

function generateTanstackQueryCode(
	spec: ParsedSpec,
	apiImportPath: string,
	typesImportPath?: string,
	hasTypes?: boolean,
): string {
	const lines: string[] = [];
	lines.push("// Generated by fizzyx. Do not edit.");
	lines.push("");

	const hasGet = spec.endpoints.some((ep) => ep.method === "get");
	const hasNonGet = spec.endpoints.some((ep) => ep.method !== "get");
	const queryImports: string[] = [];
	if (hasGet) queryImports.push("useQuery");
	if (hasNonGet) queryImports.push("useMutation");
	if (queryImports.length > 0) {
		lines.push(`import { ${queryImports.join(", ")} } from "@tanstack/react-query"`);
	}

	const fnImports: string[] = [];
	const apiTypeImports: string[] = [];
	const typesTypeImports: string[] = [];

	for (const ep of spec.endpoints) {
		const fnName = toFnName(ep);
		fnImports.push(fnName);

		const prefix = toPascalCase(fnName);
		if (ep.queryParams.length > 0) {
			apiTypeImports.push(`${prefix}QueryParams`);
		}
		if (ep.pathParams.length > 0) {
			apiTypeImports.push(`${prefix}PathParams`);
		}
		if (ep.method !== "get" && ep.bodyTypeRef) {
			typesTypeImports.push(ep.bodyTypeRef);
		}
	}

	const uniqueFns = [...new Set(fnImports)];
	lines.push(`import { ${uniqueFns.join(", ")} } from "${apiImportPath}"`);

	const uniqueApiTypes = [...new Set(apiTypeImports)];
	if (uniqueApiTypes.length > 0) {
		lines.push(`import type { ${uniqueApiTypes.join(", ")} } from "${apiImportPath}"`);
	}

	const uniqueTypesTypes = [...new Set(typesTypeImports)];
	if (uniqueTypesTypes.length > 0 && hasTypes && typesImportPath) {
		lines.push(`import type { ${uniqueTypesTypes.join(", ")} } from "${typesImportPath}"`);
	}

	lines.push("");

	for (const ep of spec.endpoints) {
		const fnName = toFnName(ep);

		if (ep.method === "get") {
			lines.push(generateQueryKey(ep, fnName));
			lines.push("");
			lines.push(generateQueryOptions(ep, fnName));
			lines.push("");
			lines.push(generateQueryHook(ep, fnName));
		} else {
			lines.push(generateMutationOptions(ep, fnName));
			lines.push("");
			lines.push(generateMutationHook(ep, fnName));
		}
		lines.push("");
	}

	return lines.join("\n");
}

function paramSignature(ep: ParsedEndpoint): string[] {
	const parts: string[] = [];
	const prefix = toPascalCase(toFnName(ep));

	if (ep.pathParams.length > 0) {
		parts.push(`params: ${prefix}PathParams`);
	}
	if (ep.queryParams.length > 0) {
		parts.push(`query?: ${prefix}QueryParams`);
	}
	return parts;
}

function queryKeyFields(ep: ParsedEndpoint): string[] {
	const fields: string[] = [`scope: ${JSON.stringify(toFnName(ep))}`];
	if (ep.pathParams.length > 0) {
		fields.push("params");
	}
	if (ep.queryParams.length > 0) {
		fields.push("query");
	}
	return fields;
}

function generateQueryKey(ep: ParsedEndpoint, fnName: string): string {
	const params = paramSignature(ep);
	const keyFields = queryKeyFields(ep);
	const fnSig = params.length > 0 ? `(${params.join(", ")})` : "()";
	return `export function ${fnName}QueryKey${fnSig} {\n  return [{ ${keyFields.join(", ")} }] as const\n}`;
}

function forwardArgs(ep: ParsedEndpoint): string {
	const args: string[] = [];
	if (ep.pathParams.length > 0) {
		args.push("params");
	}
	if (ep.bodyTypeRef) {
		args.push("data");
	}
	if (ep.queryParams.length > 0) {
		args.push("query");
	}
	return args.length > 0 ? args.join(", ") : "";
}

function generateQueryOptions(ep: ParsedEndpoint, fnName: string): string {
	const params = paramSignature(ep);
	const fnSig = params.length > 0 ? `(${params.join(", ")})` : "()";
	const fwd = forwardArgs(ep);
	return `export function ${fnName}Options${fnSig} {\n  return {\n    queryKey: ${fnName}QueryKey(${fwd}),\n    queryFn: () => ${fnName}(${fwd}),\n  }\n}`;
}

function generateQueryHook(ep: ParsedEndpoint, fnName: string): string {
	const params = paramSignature(ep);
	const fnSig = params.length > 0 ? `(${params.join(", ")})` : "()";
	const fwd = forwardArgs(ep);
	return `export function use${toPascalCase(fnName)}${fnSig} {\n  return useQuery(${fnName}Options(${fwd}))\n}`;
}

function mutationParamInfo(ep: ParsedEndpoint): { args: string; call: string } {
	const fnName = toFnName(ep);
	const prefix = toPascalCase(fnName);
	const hasBody = !!ep.bodyTypeRef;
	const hasPath = ep.pathParams.length > 0;
	const hasQuery = ep.queryParams.length > 0;

	const parts: { name: string; type: string }[] = [];
	if (hasPath) parts.push({ name: "params", type: `${prefix}PathParams` });
	if (hasBody) parts.push({ name: "data", type: ep.bodyTypeRef! });
	if (hasQuery) parts.push({ name: "query", type: `${prefix}QueryParams` });

	if (parts.length === 0) {
		return { args: "", call: `${fnName}()` };
	}

	if (parts.length === 1) {
		const p = parts[0]!;
		return {
			args: `${p.name}: ${p.type}`,
			call: `${fnName}(${p.name})`,
		};
	}

	const innerNames = parts.map((p) => p.name);
	const combinedType = `{ ${parts.map((p) => `${p.name}: ${p.type}`).join("; ")} }`;
	return {
		args: `{ ${innerNames.join(", ")} }: ${combinedType}`,
		call: `${fnName}(${innerNames.join(", ")})`,
	};
}

function generateMutationOptions(ep: ParsedEndpoint, fnName: string): string {
	const info = mutationParamInfo(ep);
	const body = info.args
		? `mutationFn: (${info.args}) => ${info.call}`
		: `mutationFn: () => ${info.call}`;

	return `export function ${fnName}Mutation() {\n  return {\n    ${body},\n  }\n}`;
}

function generateMutationHook(_ep: ParsedEndpoint, fnName: string): string {
	return `export function use${toPascalCase(fnName)}() {\n  return useMutation(${fnName}Mutation())\n}`;
}
