import { Effect } from "effect";
import { CodegenError } from "../domain/errors";
import { toFnName, toPascalCase } from "../domain/codegen-utils";
import type { CodeGenerator } from "../ports/code-generator";
import type {
	GenFileOptions,
	GeneratedFile,
	ParsedEndpoint,
	ParsedSpec,
} from "../domain/openapi-models";
import {
	collectUsedTypeNames,
	convertPathToTemplate,
	generateTypes,
	renderPropertyKey,
} from "./codegen-shared";

export const EFFECT_GENERATOR_DEFAULTS: GenFileOptions = {
	apiName: "effect-client.ts",
	typesName: "types.ts",
	runtimeName: "effect-http.ts",
};

const EFFECT_RUNTIME_CODE = `// effect-http — Effect 4 HTTP client
// Generated by fizzyx. Only what you use ships.

import { Effect } from "effect"
import * as FetchHttpClient from "effect/unstable/http/FetchHttpClient"
import * as HttpBody from "effect/unstable/http/HttpBody"
import * as HttpClient from "effect/unstable/http/HttpClient"
import * as HttpClientError from "effect/unstable/http/HttpClientError"
import * as HttpClientRequest from "effect/unstable/http/HttpClientRequest"
import * as HttpClientResponse from "effect/unstable/http/HttpClientResponse"

export type EffectHttpClientError =
  | HttpClientError.HttpClientError
  | HttpBody.HttpBodyError

export interface EffectClientConfig {
  /** API base URL (prepended to relative paths). */
  baseUrl?: string
  /** Default headers sent with every request. */
  headers?: Record<string, string>
  /**
   * Transform the raw response body before returning.
   * Default unwraps \`{ code, data }\` envelope → \`data\`.
   * Set to \`(raw) => raw\` to disable unwrapping.
   */
  responseExtractor?: (raw: unknown) => unknown
}

export type HttpMethod = "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS"

export const FetchLayer = FetchHttpClient.layer

let _config: EffectClientConfig = {}
let _token: string | null = null
let _defaultHeaders: Record<string, string> = {}

/** Configure the client. Call once at app startup. */
export function configure(config: EffectClientConfig): void {
  _config = { ..._config, ...config }
}

/** Set auth token. Pass \`null\` to clear. */
export function setToken(token: string | null): void {
  _token = token
}

/** Set default headers sent with every request. Merge with existing defaults. */
export function setHeaders(headers: Record<string, string>): void {
  _defaultHeaders = { ..._defaultHeaders, ...headers }
}

function defaultExtractor(raw: unknown): unknown {
  if (raw !== null && typeof raw === "object" && "code" in (raw as Record<string, unknown>) && "data" in (raw as Record<string, unknown>)) {
    return (raw as Record<string, unknown>).data
  }
  return raw
}

function buildUrl(url: string, query?: Record<string, unknown>): string {
  let finalUrl = url.startsWith("http") ? url : (_config.baseUrl ?? "") + url
  if (query) {
    const params = new URLSearchParams()
    for (const [key, val] of Object.entries(query)) {
      if (val === undefined) continue
      if (Array.isArray(val)) {
        for (const item of val) {
          if (item !== undefined) params.append(key, String(item))
        }
      } else {
        params.set(key, String(val))
      }
    }
    const qs = params.toString()
    if (qs) finalUrl += (finalUrl.includes("?") ? "&" : "?") + qs
  }
  return finalUrl
}

function readResponse(response: HttpClientResponse.HttpClientResponse): Effect.Effect<unknown, HttpClientError.HttpClientError> {
  const contentType = response.headers["content-type"] ?? ""
  return contentType.includes("application/json") ? response.json : response.text
}

/**
 * Typed Effect request using Effect 4's HttpClient service.
 *
 * Provide a transport at the program boundary, for example:
 * \`program.pipe(Effect.provide(FetchLayer))\`
 */
export function execute<T, B = unknown>(
  method: HttpMethod,
  url: string,
  options?: { query?: Record<string, unknown>; body?: B; headers?: Record<string, string> }
): Effect.Effect<T, EffectHttpClientError, HttpClient.HttpClient> {
  const httpRequest = Effect.sync(() => {
    const finalUrl = buildUrl(url, options?.query)
    const headers: Record<string, string> = {
      ..._config.headers,
      ..._defaultHeaders,
      ...options?.headers,
    }
    if (_token) headers["Authorization"] = \`Bearer \${_token}\`

    return HttpClientRequest.make(method)(finalUrl, {
      headers,
      acceptJson: true,
    })
  }).pipe(
    Effect.flatMap((baseRequest) =>
      options?.body === undefined
        ? Effect.succeed(baseRequest)
        : HttpClientRequest.bodyJson(options.body)(baseRequest)
    )
  )

  return httpRequest.pipe(
    Effect.flatMap((request) => HttpClient.execute(request)),
    Effect.flatMap(HttpClientResponse.filterStatusOk),
    Effect.flatMap(readResponse),
    Effect.map((raw) => {
      const extractor = _config.responseExtractor || defaultExtractor
      return extractor(raw) as T
    })
  )
}
`;

export const effectGenerator: CodeGenerator = {
	name: "effect",
	info: { name: "effect", description: "Effect 4 HTTP client (effect/unstable/http)" },

	generate: (spec: ParsedSpec, output: string, options?: GenFileOptions) =>
		Effect.gen(function* () {
			try {
				const opts = {
					apiName: options?.apiName ?? EFFECT_GENERATOR_DEFAULTS.apiName,
					typesName: options?.typesName ?? EFFECT_GENERATOR_DEFAULTS.typesName,
					runtimeName: options?.runtimeName ?? EFFECT_GENERATOR_DEFAULTS.runtimeName,
				} as Required<GenFileOptions>;
				const files: GeneratedFile[] = [];

				const typesCode = generateTypes(spec);
				const hasTypes = spec.types && Object.keys(spec.types).length > 0;

				const typesFile = opts.typesName === false ? undefined : opts.typesName;
				const typesImportPath = typesFile ? `./${typesFile.replace(/\.ts$/, "")}` : undefined;

				const runtimeFile = opts.runtimeName;
				const runtimeImportPath = `./${runtimeFile.replace(/\.ts$/, "")}`;

				const apiCode = generateEffectApi(spec, runtimeImportPath, typesImportPath, hasTypes);

				if (hasTypes && typesFile) {
					files.push({ path: typesFile, content: typesCode });
				}

				files.push({ path: runtimeFile, content: EFFECT_RUNTIME_CODE });
				files.push({ path: opts.apiName, content: apiCode });

				return files;
			} catch (e) {
				return yield* Effect.fail(
					new CodegenError({
						message: `effect codegen failed: ${e instanceof Error ? e.message : String(e)}`,
						target: "effect",
						cause: e,
					}),
				);
			}
		}),
};

function generateEffectApi(
	spec: ParsedSpec,
	runtimeImportPath: string,
	typesImportPath: string | undefined,
	hasTypes: boolean,
): string {
	const lines: string[] = [];
	lines.push("// Generated by fizzyx. Do not edit.");
	lines.push("");
	lines.push(`import { Effect } from "effect"`);
	lines.push(`import * as HttpClient from "effect/unstable/http/HttpClient"`);
	lines.push(`import { execute } from "${runtimeImportPath}"`);
	lines.push(`import type { EffectHttpClientError } from "${runtimeImportPath}"`);
	lines.push(
		`export type { EffectClientConfig, EffectHttpClientError, HttpMethod } from "${runtimeImportPath}"`,
	);
	lines.push(`export { FetchLayer, configure, setToken, setHeaders } from "${runtimeImportPath}"`);
	const usedTypeNames = collectUsedTypeNames(spec);
	if (hasTypes && typesImportPath && usedTypeNames.length > 0) {
		lines.push(`import type { ${usedTypeNames.join(", ")} } from "${typesImportPath}"`);
	}
	lines.push("");

	const needsBaseParams = spec.endpoints.some(
		(e) => e.pathParams.length > 0 || e.queryParams.length > 0,
	);
	if (needsBaseParams) {
		lines.push("export interface BaseParams {");
		lines.push("  [key: string]: unknown");
		lines.push("}");
		lines.push("");
	}

	for (const endpoint of spec.endpoints) {
		lines.push(renderEffectEndpoint(endpoint));
	}

	return lines.join("\n");
}

function renderEffectEndpoint(endpoint: ParsedEndpoint): string {
	const { method, path, pathParams, queryParams, bodyTypeRef, responseTypeRef } = endpoint;

	const fnName = toFnName(endpoint);
	const typePrefix = toPascalCase(fnName);
	const tsPath = convertPathToTemplate(
		path,
		pathParams.map((p) => p.name),
		pathParams.length > 0,
	);

	const hasBody = bodyTypeRef !== undefined;
	const hasPathParams = pathParams.length > 0;
	const hasQueryParams = queryParams.length > 0;
	const responseType = responseTypeRef ?? "void";

	const typeLines: string[] = [];
	const allParams: string[] = [];
	const jsdocLines: string[] = [];

	if (endpoint.description) {
		jsdocLines.push(endpoint.description);
	}

	if (hasPathParams) {
		const typeName = `${typePrefix}PathParams`;
		typeLines.push(`export interface ${typeName} extends BaseParams {`);
		for (const p of pathParams) {
			if (p.description) {
				typeLines.push(`  /** ${p.description} */`);
			}
			typeLines.push(`  ${renderPropertyKey(p.name)}: ${p.typeRef}`);
		}
		typeLines.push("}");
		allParams.push(`params: ${typeName}`);
		for (const p of pathParams) {
			if (p.description) {
				jsdocLines.push(`@param params.${p.name} - ${p.description}`);
			}
		}
	}

	if (hasBody && bodyTypeRef) {
		allParams.push(`data: ${bodyTypeRef}`);
		jsdocLines.push("@param data - Request body");
	}

	if (hasQueryParams) {
		const typeName = `${typePrefix}QueryParams`;
		typeLines.push(`export interface ${typeName} extends BaseParams {`);
		for (const q of queryParams) {
			if (q.description) {
				typeLines.push(`  /** ${q.description} */`);
			}
			typeLines.push(`  ${renderPropertyKey(q.name)}${q.required ? "" : "?"}: ${q.typeRef}`);
		}
		typeLines.push("}");
		allParams.push(`query?: ${typeName}`);
		for (const q of queryParams) {
			if (q.description) {
				jsdocLines.push(`@param query.${q.name} - ${q.description}`);
			}
		}
	}

	const callArgs: string[] = [];
	callArgs.push(JSON.stringify(method.toUpperCase()));
	callArgs.push(`\`${tsPath}\``);

	const optsParts: string[] = [];
	if (hasQueryParams) optsParts.push("query");
	if (hasBody) optsParts.push(`body: data`);

	const typeParams =
		hasBody && bodyTypeRef ? `<${responseType}, ${bodyTypeRef}>` : `<${responseType}>`;

	const callStr =
		optsParts.length > 0
			? `execute${typeParams}(${callArgs.join(", ")}, { ${optsParts.join(", ")} })`
			: `execute${typeParams}(${callArgs.join(", ")})`;

	const fnLines: string[] = [];

	if (jsdocLines.length > 0) {
		const desc = jsdocLines.join("\n * ");
		fnLines.push(`/**\n * ${desc}\n */`);
	}

	fnLines.push(
		`export function ${fnName}(${allParams.join(", ")}): Effect.Effect<${responseType}, EffectHttpClientError, HttpClient.HttpClient> {`,
	);
	fnLines.push(`  return ${callStr}`);
	fnLines.push("}");

	const resultLines = typeLines.length > 0 ? [...typeLines, ...fnLines] : fnLines;
	return resultLines.join("\n");
}
