import type { AdminAppPlan, AdminResourcePlan } from "../domain/openapi-admin-models";
import type { GeneratedFile } from "../domain/openapi-models";
import { toPascalCase } from "../domain/codegen-utils";
import type { AdminFramework } from "./openapi-admin-scaffold";
import { renderTemplate } from "./openapi-admin-template";
import adminShellTemplate from "../templates/openapi-admin/shared/admin-shell.tsx.txt" with { type: "text" };
import dataTableTemplate from "../templates/openapi-admin/shared/data-table.tsx.txt" with { type: "text" };
import dynamicFormTemplate from "../templates/openapi-admin/shared/dynamic-form.tsx.txt" with { type: "text" };
import queryProviderTemplate from "../templates/openapi-admin/shared/query-provider.tsx.txt" with { type: "text" };
import adminApiTemplate from "../templates/openapi-admin/shared/admin-api.ts.txt" with { type: "text" };
import nextLayoutTemplate from "../templates/openapi-admin/nextjs/layout.tsx.txt" with { type: "text" };
import nextListTemplate from "../templates/openapi-admin/nextjs/list-page.tsx.txt" with { type: "text" };
import nextCreateTemplate from "../templates/openapi-admin/nextjs/create-page.tsx.txt" with { type: "text" };
import nextDetailTemplate from "../templates/openapi-admin/nextjs/detail-page.tsx.txt" with { type: "text" };
import nextEditTemplate from "../templates/openapi-admin/nextjs/edit-page.tsx.txt" with { type: "text" };
import tanstackLayoutTemplate from "../templates/openapi-admin/tanstack-start/layout-route.tsx.txt" with { type: "text" };
import tanstackListTemplate from "../templates/openapi-admin/tanstack-start/list-route.tsx.txt" with { type: "text" };
import tanstackCreateTemplate from "../templates/openapi-admin/tanstack-start/create-route.tsx.txt" with { type: "text" };
import tanstackDetailTemplate from "../templates/openapi-admin/tanstack-start/detail-route.tsx.txt" with { type: "text" };
import tanstackEditTemplate from "../templates/openapi-admin/tanstack-start/edit-route.tsx.txt" with { type: "text" };

const identifier = (value: string): string => {
	if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value)) {
		throw new Error(`unsafe generated TypeScript identifier: ${value}`);
	}
	return value;
};

const componentName = (prefix: string, resource: AdminResourcePlan): string =>
	identifier(`${prefix}${toPascalCase(resource.id)}Page`);

const hookName = (operationId: string): string => identifier(`use${toPascalCase(operationId)}`);

const renderPlan = (plan: AdminAppPlan): GeneratedFile => ({
	path: "src/generated/admin-plan.ts",
	content: `// Generated by fizzyx. Do not edit.\n\nexport const adminPlan = ${JSON.stringify(
		{
			title: plan.title,
			resources: plan.resources.map(({ id, label, path }) => ({ id, label, path })),
			diagnostics: plan.diagnostics,
		},
		null,
		2,
	)} as const\n`,
});

const staticFile = (path: string, template: string): GeneratedFile => ({
	path,
	content: renderTemplate(template, {}),
});

const formFields = (resource: AdminResourcePlan) =>
	resource.fields.map((field) => {
		const control =
			field.format === "email"
				? "email"
				: field.format === "uri" || field.format === "url"
					? "url"
					: field.format === "date"
						? "date"
						: field.format === "date-time"
							? "datetime-local"
							: field.tsType.includes("number")
								? "number"
								: field.tsType.includes("boolean")
									? "checkbox"
									: "text";
		return {
			name: field.name,
			label: field.name.replace(/[-_]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()),
			control,
			required: field.required,
			description: field.description,
			minimum: field.minimum,
			maximum: field.maximum,
			minLength: field.minLength,
			maxLength: field.maxLength,
			pattern: field.pattern,
		};
	});

const columnsLiteral = (resource: AdminResourcePlan): string =>
	JSON.stringify(resource.columns.map((column) => ({ key: column.name, label: column.name })));

const hookArgs = (resource: AdminResourcePlan): string =>
	resource.operations.list?.endpoint.queryParams.length ? "({})" : "()";

const propertyKey = (value: string): string =>
	/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);

const listTableValues = (resource: AdminResourcePlan) => {
	const mapping = resource.listQuery;
	if (!mapping) {
		return {
			FIZZYX_REACT_IMPORT: "",
			FIZZYX_TABLE_TYPE_IMPORT: "",
			FIZZYX_STATE_DECLARATION: "",
			FIZZYX_HOOK_ARGS: hookArgs(resource),
			FIZZYX_TABLE_PROPS: "",
		};
	}
	const query: string[] = [];
	if (mapping.page) query.push(`${propertyKey(mapping.page)}: tableState.pagination.pageIndex + 1`);
	if (mapping.offset)
		query.push(
			`${propertyKey(mapping.offset)}: tableState.pagination.pageIndex * tableState.pagination.pageSize`,
		);
	if (mapping.limit) query.push(`${propertyKey(mapping.limit)}: tableState.pagination.pageSize`);
	if (mapping.search)
		query.push(`${propertyKey(mapping.search)}: tableState.globalFilter || undefined`);
	if (mapping.sort) query.push(`${propertyKey(mapping.sort)}: tableState.sorting[0]?.id`);
	if (mapping.order)
		query.push(
			`${propertyKey(mapping.order)}: tableState.sorting[0] ? (tableState.sorting[0].desc ? "desc" : "asc") : undefined`,
		);
	for (const filter of mapping.filters) {
		query.push(
			`${propertyKey(filter)}: tableState.columnFilters.find(({ id }) => id === ${JSON.stringify(filter)})?.value`,
		);
	}
	return {
		FIZZYX_REACT_IMPORT: 'import { useState } from "react"\n',
		FIZZYX_TABLE_TYPE_IMPORT: ", type AdminDataTableState",
		FIZZYX_STATE_DECLARATION:
			'const [tableState, setTableState] = useState<AdminDataTableState>({ pagination: { pageIndex: 0, pageSize: 20 }, sorting: [], columnFilters: [], globalFilter: "" })',
		FIZZYX_HOOK_ARGS: `({ ${query.join(", ")} } as never)`,
		FIZZYX_TABLE_PROPS: ' mode="server" state={tableState} onStateChange={setTableState}',
	};
};

const renderNextList = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const operation = resource.operations.list;
	if (!operation) return undefined;
	const hook = hookName(operation.operationId);
	const tableValues = listTableValues(resource);
	return {
		path: `src/app/(admin)/${resource.id}/page.tsx`,
		content: renderTemplate(nextListTemplate, {
			FIZZYX_HOOK_NAME: hook,
			FIZZYX_COLUMNS: columnsLiteral(resource),
			FIZZYX_LABEL: JSON.stringify(resource.label),
			FIZZYX_COMPONENT_NAME: componentName("", resource),
			...tableValues,
		}),
	};
};

const renderNextCreate = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const operation = resource.operations.create;
	if (!operation) return undefined;
	return {
		path: `src/app/(admin)/${resource.id}/new/page.tsx`,
		content: renderTemplate(nextCreateTemplate, {
			FIZZYX_HOOK_NAME: hookName(operation.operationId),
			FIZZYX_FIELDS: JSON.stringify(formFields(resource)),
			FIZZYX_LABEL: JSON.stringify(resource.label),
			FIZZYX_COMPONENT_NAME: componentName("New", resource),
		}),
	};
};

const detailValues = (resource: AdminResourcePlan, framework: AdminFramework) => {
	const detail = resource.operations.detail;
	if (!detail) return undefined;
	const detailHook = hookName(detail.operationId);
	const remove = resource.operations.delete;
	const deleteHook = remove ? hookName(remove.operationId) : undefined;
	return {
		FIZZYX_ROUTE: JSON.stringify(`/_admin/${resource.id}/$id`),
		FIZZYX_HOOK_IMPORTS: [detailHook, deleteHook].filter(Boolean).join(", "),
		FIZZYX_ID_PARAM: JSON.stringify(resource.idParam ?? "id"),
		FIZZYX_LABEL: JSON.stringify(resource.label),
		FIZZYX_COMPONENT_NAME: componentName("", resource),
		FIZZYX_DETAIL_HOOK: detailHook,
		FIZZYX_DELETE_DECLARATION: deleteHook ? `const remove = ${deleteHook}()` : "",
		FIZZYX_DELETE_BUTTON: deleteHook
			? '<Button variant="destructive" disabled={remove.isPending} onClick={() => remove.mutate(params as never)}>Delete</Button>'
			: "",
		framework,
	};
};

const renderNextDetail = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const values = detailValues(resource, "nextjs");
	if (!values) return undefined;
	const { FIZZYX_ROUTE: _route, framework: _framework, ...templateValues } = values;
	return {
		path: `src/app/(admin)/${resource.id}/[id]/page.tsx`,
		content: renderTemplate(nextDetailTemplate, templateValues),
	};
};

const editValues = (resource: AdminResourcePlan) => {
	const update = resource.operations.update;
	if (!update) return undefined;
	const detail = resource.operations.detail;
	const detailHook = detail ? hookName(detail.operationId) : undefined;
	return {
		FIZZYX_ROUTE: JSON.stringify(`/_admin/${resource.id}/$id/edit`),
		FIZZYX_HOOK_IMPORTS: [hookName(update.operationId), detailHook].filter(Boolean).join(", "),
		FIZZYX_FIELDS: JSON.stringify(formFields(resource)),
		FIZZYX_ID_PARAM: JSON.stringify(resource.idParam ?? "id"),
		FIZZYX_LABEL: JSON.stringify(resource.label),
		FIZZYX_COMPONENT_NAME: componentName("Edit", resource),
		FIZZYX_DETAIL_DECLARATION: detailHook ? `const detail = ${detailHook}(params as never)` : "",
		FIZZYX_UPDATE_HOOK: hookName(update.operationId),
		FIZZYX_INITIAL_VALUE: detailHook ? "(detail.data ?? {}) as Record<string, unknown>" : "{}",
	};
};

const renderNextEdit = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const values = editValues(resource);
	if (!values) return undefined;
	const { FIZZYX_ROUTE: _route, ...templateValues } = values;
	return {
		path: `src/app/(admin)/${resource.id}/[id]/edit/page.tsx`,
		content: renderTemplate(nextEditTemplate, templateValues),
	};
};

const renderTanstackList = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const operation = resource.operations.list;
	if (!operation) return undefined;
	const tableValues = listTableValues(resource);
	return {
		path: `src/routes/_admin/${resource.id}/index.tsx`,
		content: renderTemplate(tanstackListTemplate, {
			FIZZYX_ROUTE: JSON.stringify(`/_admin/${resource.id}/`),
			FIZZYX_HOOK_NAME: hookName(operation.operationId),
			FIZZYX_COLUMNS: columnsLiteral(resource),
			FIZZYX_LABEL: JSON.stringify(resource.label),
			FIZZYX_COMPONENT_NAME: componentName("", resource),
			...tableValues,
		}),
	};
};

const renderTanstackCreate = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const operation = resource.operations.create;
	if (!operation) return undefined;
	return {
		path: `src/routes/_admin/${resource.id}/new.tsx`,
		content: renderTemplate(tanstackCreateTemplate, {
			FIZZYX_ROUTE: JSON.stringify(`/_admin/${resource.id}/new`),
			FIZZYX_HOOK_NAME: hookName(operation.operationId),
			FIZZYX_FIELDS: JSON.stringify(formFields(resource)),
			FIZZYX_LABEL: JSON.stringify(resource.label),
			FIZZYX_COMPONENT_NAME: componentName("New", resource),
		}),
	};
};

const renderTanstackDetail = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const values = detailValues(resource, "tanstack-start");
	if (!values) return undefined;
	const { framework: _framework, ...templateValues } = values;
	return {
		path: `src/routes/_admin/${resource.id}/$id.tsx`,
		content: renderTemplate(tanstackDetailTemplate, templateValues),
	};
};

const renderTanstackEdit = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const values = editValues(resource);
	if (!values) return undefined;
	return {
		path: `src/routes/_admin/${resource.id}/$id.edit.tsx`,
		content: renderTemplate(tanstackEditTemplate, values),
	};
};

const renderResources = (
	plan: AdminAppPlan,
	renderers: Array<(resource: AdminResourcePlan) => GeneratedFile | undefined>,
): GeneratedFile[] =>
	plan.resources.flatMap((resource) =>
		renderers.map((renderer) => renderer(resource)).filter((file): file is GeneratedFile => !!file),
	);

export const renderAdminApp = (plan: AdminAppPlan, framework: AdminFramework): GeneratedFile[] => {
	const apiBaseUrl =
		framework === "nextjs"
			? 'process.env.NEXT_PUBLIC_API_BASE_URL ?? ""'
			: 'import.meta.env.VITE_API_BASE_URL ?? ""';
	const shared = [
		renderPlan(plan),
		staticFile("src/components/admin/admin-shell.tsx", adminShellTemplate),
		staticFile("src/components/admin/data-table.tsx", dataTableTemplate),
		staticFile("src/components/admin/dynamic-form.tsx", dynamicFormTemplate),
		staticFile("src/components/admin/query-provider.tsx", queryProviderTemplate),
		{
			path: "src/lib/api/admin-api.ts",
			content: renderTemplate(adminApiTemplate, { FIZZYX_API_BASE_URL: apiBaseUrl }),
		},
	];
	if (framework === "nextjs") {
		return [
			...shared,
			staticFile("src/app/(admin)/layout.tsx", nextLayoutTemplate),
			...renderResources(plan, [
				renderNextList,
				renderNextCreate,
				renderNextDetail,
				renderNextEdit,
			]),
		];
	}
	return [
		...shared,
		staticFile("src/routes/_admin.tsx", tanstackLayoutTemplate),
		...renderResources(plan, [
			renderTanstackList,
			renderTanstackCreate,
			renderTanstackDetail,
			renderTanstackEdit,
		]),
	];
};
