import type { GenFileOptions, GeneratedFile, ParsedSpec } from "../domain/openapi-models";

export interface OpenApiArtifactPlan {
	apiName: string;
	typesName?: string;
	runtimeName?: string;
	apiImportPath: string;
	typesImportPath?: string;
	hasTypes: boolean;
}

export const planOpenApiArtifacts = (
	spec: ParsedSpec,
	options?: GenFileOptions,
	defaults: Required<GenFileOptions> = {
		apiName: "api.ts",
		typesName: "types.ts",
		runtimeName: "request.ts",
	},
): OpenApiArtifactPlan => {
	const apiName = options?.apiName ?? defaults.apiName;
	const rawTypesName = options?.typesName ?? defaults.typesName;
	const typesName = rawTypesName === false ? undefined : rawTypesName;
	const runtimeName = options?.runtimeName ?? defaults.runtimeName;
	const hasTypes = Boolean(typesName && spec.types && Object.keys(spec.types).length > 0);
	return {
		apiName,
		typesName,
		runtimeName,
		apiImportPath: `./${apiName.replace(/\.ts$/, "")}`,
		typesImportPath: typesName ? `./${typesName.replace(/\.ts$/, "")}` : undefined,
		hasTypes,
	};
};

export const generateIndexFile = (
	plan: Pick<OpenApiArtifactPlan, "apiImportPath" | "typesImportPath" | "hasTypes">,
	extensionExports: ReadonlyArray<string>,
): GeneratedFile => ({
	path: "index.ts",
	content: [
		"// Generated by fizzyx. Do not edit.",
		"",
		`export * from "${plan.apiImportPath}"`,
		...(plan.typesImportPath && plan.hasTypes ? [`export * from "${plan.typesImportPath}"`] : []),
		...extensionExports.map((exportPath) => `export * from "${exportPath}"`),
		"",
	].join("\n"),
});
