import type { AdminAppPlan, AdminResourcePlan } from "../domain/openapi-admin-models";
import type { GeneratedFile } from "../domain/openapi-models";
import { toPascalCase } from "../domain/codegen-utils";
import type { AdminFramework } from "./openapi-admin-scaffold";
import { renderTemplate } from "./openapi-admin-template";
import adminShellTemplate from "../templates/openapi-admin/shared/admin-shell.tsx.txt" with { type: "text" };
import authAdminShellTemplate from "../templates/openapi-admin/shared/auth-admin-shell.tsx.txt" with { type: "text" };
import dataTableTemplate from "../templates/openapi-admin/shared/data-table.tsx.txt" with { type: "text" };
import dynamicFormTemplate from "../templates/openapi-admin/shared/dynamic-form.tsx.txt" with { type: "text" };
import queryProviderTemplate from "../templates/openapi-admin/shared/query-provider.tsx.txt" with { type: "text" };
import adminApiTemplate from "../templates/openapi-admin/shared/admin-api.ts.txt" with { type: "text" };
import nextLayoutTemplate from "../templates/openapi-admin/nextjs/layout.tsx.txt" with { type: "text" };
import nextListTemplate from "../templates/openapi-admin/nextjs/list-page.tsx.txt" with { type: "text" };
import nextCreateTemplate from "../templates/openapi-admin/nextjs/create-page.tsx.txt" with { type: "text" };
import nextDetailTemplate from "../templates/openapi-admin/nextjs/detail-page.tsx.txt" with { type: "text" };
import nextEditTemplate from "../templates/openapi-admin/nextjs/edit-page.tsx.txt" with { type: "text" };
import tanstackLayoutTemplate from "../templates/openapi-admin/tanstack-start/layout-route.tsx.txt" with { type: "text" };
import tanstackListTemplate from "../templates/openapi-admin/tanstack-start/list-route.tsx.txt" with { type: "text" };
import tanstackCreateTemplate from "../templates/openapi-admin/tanstack-start/create-route.tsx.txt" with { type: "text" };
import tanstackDetailTemplate from "../templates/openapi-admin/tanstack-start/detail-route.tsx.txt" with { type: "text" };
import tanstackEditTemplate from "../templates/openapi-admin/tanstack-start/edit-route.tsx.txt" with { type: "text" };
import nextAuthLayoutTemplate from "../templates/openapi-admin/nextjs/auth-layout.tsx.txt" with { type: "text" };
import nextAuthServerTemplate from "../templates/openapi-admin/nextjs/auth-server.ts.txt" with { type: "text" };
import nextLoginRouteTemplate from "../templates/openapi-admin/nextjs/login-route.ts.txt" with { type: "text" };
import nextLogoutRouteTemplate from "../templates/openapi-admin/nextjs/logout-route.ts.txt" with { type: "text" };
import nextProxyRouteTemplate from "../templates/openapi-admin/nextjs/proxy-route.ts.txt" with { type: "text" };
import nextLoginPageTemplate from "../templates/openapi-admin/nextjs/login-page.tsx.txt" with { type: "text" };
import tanstackAuthLayoutTemplate from "../templates/openapi-admin/tanstack-start/auth-layout-route.tsx.txt" with { type: "text" };
import tanstackAuthServerTemplate from "../templates/openapi-admin/tanstack-start/auth-server.ts.txt" with { type: "text" };
import tanstackAuthSessionTemplate from "../templates/openapi-admin/tanstack-start/auth-session.server.ts.txt" with { type: "text" };
import tanstackLoginApiTemplate from "../templates/openapi-admin/tanstack-start/login-api-route.ts.txt" with { type: "text" };
import tanstackLogoutApiTemplate from "../templates/openapi-admin/tanstack-start/logout-api-route.ts.txt" with { type: "text" };
import tanstackProxyTemplate from "../templates/openapi-admin/tanstack-start/proxy-route.ts.txt" with { type: "text" };
import tanstackLoginTemplate from "../templates/openapi-admin/tanstack-start/login-route.tsx.txt" with { type: "text" };
import adminAuthSkillTemplate from "../templates/openapi-admin/skills/fizzyx-openapi-admin-auth/SKILL.md" with { type: "text" };
import adminAuthSkillMetadataTemplate from "../templates/openapi-admin/skills/fizzyx-openapi-admin-auth/agents/openai.yaml" with { type: "text" };
import adminDevelopmentSkillTemplate from "../templates/openapi-admin/skills/fizzyx-openapi-admin-development/SKILL.md" with { type: "text" };
import adminDevelopmentSkillMetadataTemplate from "../templates/openapi-admin/skills/fizzyx-openapi-admin-development/agents/openai.yaml" with { type: "text" };

const identifier = (value: string): string => {
	if (!/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value)) {
		throw new Error(`unsafe generated TypeScript identifier: ${value}`);
	}
	return value;
};

const componentName = (prefix: string, resource: AdminResourcePlan): string =>
	identifier(`${prefix}${toPascalCase(resource.id)}Page`);

const hookName = (operationId: string): string => identifier(`use${toPascalCase(operationId)}`);

const renderPlan = (plan: AdminAppPlan): GeneratedFile => ({
	path: "src/generated/admin-plan.ts",
	content: `// Generated by fizzyx. Do not edit.\n\nexport const adminPlan = ${JSON.stringify(
		{
			title: plan.title,
			auth: plan.auth,
			resources: plan.resources.map(({ id, label, path }) => ({ id, label, path })),
			diagnostics: plan.diagnostics,
		},
		null,
		2,
	)} as const\n`,
});

const staticFile = (path: string, template: string): GeneratedFile => ({
	path,
	content: renderTemplate(template, {}),
});

const authTemplateValues = (plan: AdminAppPlan) => {
	const config = plan.auth.status === "configured" ? plan.auth.config : undefined;
	if (!config || !config.usernameField || !config.passwordField || !config.accessTokenPath) {
		return undefined;
	}
	const operationPath = plan.auth.loginPath;
	if (!operationPath) throw new Error("configured auth plan is missing its login path");
	return {
		FIZZYX_AUTH_CONFIG: JSON.stringify({
			loginPath: operationPath,
			accessTokenPath: config.accessTokenPath,
			refreshTokenPath: config.refreshTokenPath ?? "",
		}),
		FIZZYX_USERNAME_FIELD: JSON.stringify(config.usernameField),
		FIZZYX_PASSWORD_FIELD: JSON.stringify(config.passwordField),
		FIZZYX_USERNAME_LABEL: config.usernameField === "email" ? "Email" : "Username",
		FIZZYX_USERNAME_TYPE: JSON.stringify(config.usernameField === "email" ? "email" : "text"),
		FIZZYX_LOGIN_ROUTE: JSON.stringify(config.routes.login),
		FIZZYX_AFTER_LOGIN_ROUTE: JSON.stringify(config.routes.afterLogin),
	};
};

const renderAuthTemplate = (template: string, values: Record<string, string>): string =>
	renderTemplate(
		template,
		Object.fromEntries(Object.entries(values).filter(([name]) => template.includes(`{{${name}}}`))),
	);

const formFields = (resource: AdminResourcePlan) =>
	resource.fields.map((field) => {
		const control =
			field.format === "email"
				? "email"
				: field.format === "uri" || field.format === "url"
					? "url"
					: field.format === "date"
						? "date"
						: field.format === "date-time"
							? "datetime-local"
							: field.tsType.includes("number")
								? "number"
								: field.tsType.includes("boolean")
									? "checkbox"
									: "text";
		return {
			name: field.name,
			label: field.name.replace(/[-_]+/g, " ").replace(/\b\w/g, (letter) => letter.toUpperCase()),
			control,
			required: field.required,
			description: field.description,
			minimum: field.minimum,
			maximum: field.maximum,
			minLength: field.minLength,
			maxLength: field.maxLength,
			pattern: field.pattern,
		};
	});

const columnsLiteral = (resource: AdminResourcePlan): string =>
	JSON.stringify(resource.columns.map((column) => ({ key: column.name, label: column.name })));

const hookArgs = (resource: AdminResourcePlan): string =>
	resource.operations.list?.endpoint.queryParams.length ? "({})" : "()";

const propertyKey = (value: string): string =>
	/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(value) ? value : JSON.stringify(value);

const listTableValues = (resource: AdminResourcePlan) => {
	const mapping = resource.listQuery;
	if (!mapping) {
		return {
			FIZZYX_REACT_IMPORT: "",
			FIZZYX_TABLE_TYPE_IMPORT: "",
			FIZZYX_STATE_DECLARATION: "",
			FIZZYX_HOOK_ARGS: hookArgs(resource),
			FIZZYX_TABLE_PROPS: "",
		};
	}
	const query: string[] = [];
	if (mapping.page) query.push(`${propertyKey(mapping.page)}: tableState.pagination.pageIndex + 1`);
	if (mapping.offset)
		query.push(
			`${propertyKey(mapping.offset)}: tableState.pagination.pageIndex * tableState.pagination.pageSize`,
		);
	if (mapping.limit) query.push(`${propertyKey(mapping.limit)}: tableState.pagination.pageSize`);
	if (mapping.search)
		query.push(`${propertyKey(mapping.search)}: tableState.globalFilter || undefined`);
	if (mapping.sort) query.push(`${propertyKey(mapping.sort)}: tableState.sorting[0]?.id`);
	if (mapping.order)
		query.push(
			`${propertyKey(mapping.order)}: tableState.sorting[0] ? (tableState.sorting[0].desc ? "desc" : "asc") : undefined`,
		);
	for (const filter of mapping.filters) {
		query.push(
			`${propertyKey(filter)}: tableState.columnFilters.find(({ id }) => id === ${JSON.stringify(filter)})?.value`,
		);
	}
	return {
		FIZZYX_REACT_IMPORT: 'import { useState } from "react"\n',
		FIZZYX_TABLE_TYPE_IMPORT: ", type AdminDataTableState",
		FIZZYX_STATE_DECLARATION:
			'const [tableState, setTableState] = useState<AdminDataTableState>({ pagination: { pageIndex: 0, pageSize: 20 }, sorting: [], columnFilters: [], globalFilter: "" })',
		FIZZYX_HOOK_ARGS: `({ ${query.join(", ")} } as never)`,
		FIZZYX_TABLE_PROPS: ' mode="server" state={tableState} onStateChange={setTableState}',
	};
};

const listRowIdKey = (resource: AdminResourcePlan): string => {
	const pathParam = resource.idParam ?? "id";
	if (resource.columns.some((column) => column.name === pathParam)) return pathParam;
	return resource.columns.find((column) => column.name.toLowerCase() === "id")?.name ?? pathParam;
};

const nextListNavigationValues = (resource: AdminResourcePlan) => {
	const canCreate = Boolean(resource.operations.create);
	const canView = Boolean(resource.operations.detail);
	const canEdit = Boolean(resource.operations.update);
	const hasActions = canCreate || canView || canEdit;
	const idKey = listRowIdKey(resource);
	const rowActions =
		canView || canEdit
			? ` renderRowActions={(row) => { const value = row[${JSON.stringify(idKey)}]; if (value == null) return null; const id = encodeURIComponent(String(value)); return <div className="flex items-center gap-2">${canView ? `<Link className={buttonVariants({ size: "sm", variant: "outline" })} href={\`/${resource.id}/\${id}\`}>View</Link>` : ""}${canEdit ? `<Link className={buttonVariants({ size: "sm", variant: "outline" })} href={\`/${resource.id}/\${id}/edit\`}>Edit</Link>` : ""}</div> }}`
			: "";
	return {
		FIZZYX_NAV_IMPORTS: hasActions
			? 'import Link from "next/link"\nimport { buttonVariants } from "@/components/ui/button"\n'
			: "",
		FIZZYX_CREATE_ACTION: canCreate
			? `<Link className={buttonVariants()} href=${JSON.stringify(`/${resource.id}/new`)}>New ${resource.label}</Link>`
			: "",
		FIZZYX_ROW_ACTIONS: rowActions,
	};
};

const tanstackListNavigationValues = (resource: AdminResourcePlan) => {
	const canCreate = Boolean(resource.operations.create);
	const canView = Boolean(resource.operations.detail);
	const canEdit = Boolean(resource.operations.update);
	const hasActions = canCreate || canView || canEdit;
	const idKey = listRowIdKey(resource);
	const rowActions =
		canView || canEdit
			? ` renderRowActions={(row) => { const value = row[${JSON.stringify(idKey)}]; if (value == null) return null; const id = String(value); return <div className="flex items-center gap-2">${canView ? `<Link className={buttonVariants({ size: "sm", variant: "outline" })} to=${JSON.stringify(`/${resource.id}/$id`)} params={{ id }}>View</Link>` : ""}${canEdit ? `<Link className={buttonVariants({ size: "sm", variant: "outline" })} to=${JSON.stringify(`/${resource.id}/$id/edit`)} params={{ id }}>Edit</Link>` : ""}</div> }}`
			: "";
	return {
		FIZZYX_ROUTER_IMPORTS: hasActions ? ", Link" : "",
		FIZZYX_BUTTON_IMPORT: hasActions
			? 'import { buttonVariants } from "@/components/ui/button"\n'
			: "",
		FIZZYX_CREATE_ACTION: canCreate
			? `<Link className={buttonVariants()} to=${JSON.stringify(`/${resource.id}/new`)}>New ${resource.label}</Link>`
			: "",
		FIZZYX_ROW_ACTIONS: rowActions,
	};
};

const renderNextList = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const operation = resource.operations.list;
	if (!operation) return undefined;
	const hook = hookName(operation.operationId);
	const tableValues = listTableValues(resource);
	return {
		path: `src/app/(admin)/${resource.id}/page.tsx`,
		content: renderTemplate(nextListTemplate, {
			FIZZYX_HOOK_NAME: hook,
			FIZZYX_COLUMNS: columnsLiteral(resource),
			FIZZYX_LABEL: JSON.stringify(resource.label),
			FIZZYX_COMPONENT_NAME: componentName("", resource),
			...nextListNavigationValues(resource),
			...tableValues,
		}),
	};
};

const renderNextCreate = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const operation = resource.operations.create;
	if (!operation) return undefined;
	return {
		path: `src/app/(admin)/${resource.id}/new/page.tsx`,
		content: renderTemplate(nextCreateTemplate, {
			FIZZYX_HOOK_NAME: hookName(operation.operationId),
			FIZZYX_FIELDS: JSON.stringify(formFields(resource)),
			FIZZYX_LABEL: JSON.stringify(resource.label),
			FIZZYX_COMPONENT_NAME: componentName("New", resource),
		}),
	};
};

const detailValues = (resource: AdminResourcePlan, framework: AdminFramework) => {
	const detail = resource.operations.detail;
	if (!detail) return undefined;
	const detailHook = hookName(detail.operationId);
	const remove = resource.operations.delete;
	const deleteHook = remove ? hookName(remove.operationId) : undefined;
	const listRoute = JSON.stringify(`/${resource.id}`);
	return {
		FIZZYX_ROUTE: JSON.stringify(`/_admin/${resource.id}/$id`),
		FIZZYX_HOOK_IMPORTS: [detailHook, deleteHook].filter(Boolean).join(", "),
		FIZZYX_ID_PARAM: JSON.stringify(resource.idParam ?? "id"),
		FIZZYX_LABEL: JSON.stringify(resource.label),
		FIZZYX_COMPONENT_NAME: componentName("", resource),
		FIZZYX_DETAIL_HOOK: detailHook,
		FIZZYX_ROUTER_IMPORTS: deleteHook
			? framework === "nextjs"
				? ", useRouter"
				: ", useNavigate"
			: "",
		FIZZYX_NAV_DECLARATION: deleteHook
			? framework === "nextjs"
				? "const router = useRouter()"
				: "const navigate = useNavigate()"
			: "",
		FIZZYX_DELETE_DECLARATION: deleteHook ? `const remove = ${deleteHook}()` : "",
		FIZZYX_DELETE_BUTTON: deleteHook
			? framework === "nextjs"
				? `<Button variant="destructive" disabled={remove.isPending} onClick={async () => { await remove.mutateAsync(params as never); router.replace(${listRoute}); router.refresh() }}>Delete</Button>`
				: `<Button variant="destructive" disabled={remove.isPending} onClick={async () => { await remove.mutateAsync(params as never); await navigate({ to: ${listRoute} }) }}>Delete</Button>`
			: "",
		framework,
	};
};

const renderNextDetail = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const values = detailValues(resource, "nextjs");
	if (!values) return undefined;
	const { FIZZYX_ROUTE: _route, framework: _framework, ...templateValues } = values;
	return {
		path: `src/app/(admin)/${resource.id}/[id]/page.tsx`,
		content: renderTemplate(nextDetailTemplate, templateValues),
	};
};

const editValues = (resource: AdminResourcePlan) => {
	const update = resource.operations.update;
	if (!update) return undefined;
	const detail = resource.operations.detail;
	const detailHook = detail ? hookName(detail.operationId) : undefined;
	return {
		FIZZYX_ROUTE: JSON.stringify(`/_admin/${resource.id}/$id/edit`),
		FIZZYX_HOOK_IMPORTS: [hookName(update.operationId), detailHook].filter(Boolean).join(", "),
		FIZZYX_FIELDS: JSON.stringify(formFields(resource)),
		FIZZYX_ID_PARAM: JSON.stringify(resource.idParam ?? "id"),
		FIZZYX_LABEL: JSON.stringify(resource.label),
		FIZZYX_COMPONENT_NAME: componentName("Edit", resource),
		FIZZYX_DETAIL_DECLARATION: detailHook ? `const detail = ${detailHook}(params as never)` : "",
		FIZZYX_UPDATE_HOOK: hookName(update.operationId),
		FIZZYX_INITIAL_VALUE: detailHook ? "(detail.data ?? {}) as Record<string, unknown>" : "{}",
	};
};

const renderNextEdit = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const values = editValues(resource);
	if (!values) return undefined;
	const { FIZZYX_ROUTE: _route, ...templateValues } = values;
	return {
		path: `src/app/(admin)/${resource.id}/[id]/edit/page.tsx`,
		content: renderTemplate(nextEditTemplate, templateValues),
	};
};

const renderTanstackList = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const operation = resource.operations.list;
	if (!operation) return undefined;
	const tableValues = listTableValues(resource);
	return {
		path: `src/routes/_admin/${resource.id}/index.tsx`,
		content: renderTemplate(tanstackListTemplate, {
			FIZZYX_ROUTE: JSON.stringify(`/_admin/${resource.id}/`),
			FIZZYX_HOOK_NAME: hookName(operation.operationId),
			FIZZYX_COLUMNS: columnsLiteral(resource),
			FIZZYX_LABEL: JSON.stringify(resource.label),
			FIZZYX_COMPONENT_NAME: componentName("", resource),
			...tanstackListNavigationValues(resource),
			...tableValues,
		}),
	};
};

const renderTanstackCreate = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const operation = resource.operations.create;
	if (!operation) return undefined;
	return {
		path: `src/routes/_admin/${resource.id}/new.tsx`,
		content: renderTemplate(tanstackCreateTemplate, {
			FIZZYX_ROUTE: JSON.stringify(`/_admin/${resource.id}/new`),
			FIZZYX_HOOK_NAME: hookName(operation.operationId),
			FIZZYX_FIELDS: JSON.stringify(formFields(resource)),
			FIZZYX_LABEL: JSON.stringify(resource.label),
			FIZZYX_COMPONENT_NAME: componentName("New", resource),
		}),
	};
};

const renderTanstackDetail = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const values = detailValues(resource, "tanstack-start");
	if (!values) return undefined;
	const { framework: _framework, ...templateValues } = values;
	return {
		path: `src/routes/_admin/${resource.id}/$id.tsx`,
		content: renderTemplate(tanstackDetailTemplate, templateValues),
	};
};

const renderTanstackEdit = (resource: AdminResourcePlan): GeneratedFile | undefined => {
	const values = editValues(resource);
	if (!values) return undefined;
	return {
		path: `src/routes/_admin/${resource.id}/$id.edit.tsx`,
		content: renderTemplate(tanstackEditTemplate, values),
	};
};

const renderResources = (
	plan: AdminAppPlan,
	renderers: Array<(resource: AdminResourcePlan) => GeneratedFile | undefined>,
): GeneratedFile[] =>
	plan.resources.flatMap((resource) =>
		renderers.map((renderer) => renderer(resource)).filter((file): file is GeneratedFile => !!file),
	);

const routeFilePath = (route: string): string => route.replace(/^\/+|\/+$/g, "") || "index";

const renderNextAuth = (plan: AdminAppPlan): GeneratedFile[] => {
	const values = authTemplateValues(plan);
	if (!values) return [];
	const loginRoute = routeFilePath(JSON.parse(values.FIZZYX_LOGIN_ROUTE) as string);
	return [
		{
			path: "src/lib/auth/server.ts",
			content: renderAuthTemplate(nextAuthServerTemplate, values),
		},
		{
			path: "src/app/(auth)/api/auth/login/route.ts",
			content: renderAuthTemplate(nextLoginRouteTemplate, values),
		},
		staticFile("src/app/(auth)/api/auth/logout/route.ts", nextLogoutRouteTemplate),
		staticFile("src/app/(auth)/api/admin/[...path]/route.ts", nextProxyRouteTemplate),
		{
			path: `src/app/(auth)/${loginRoute}/page.tsx`,
			content: renderAuthTemplate(nextLoginPageTemplate, values),
		},
		{
			path: "src/app/(admin)/layout.tsx",
			content: renderAuthTemplate(nextAuthLayoutTemplate, values),
		},
	];
};

const renderTanstackAuth = (plan: AdminAppPlan): GeneratedFile[] => {
	const values = authTemplateValues(plan);
	if (!values) return [];
	const loginRoute = routeFilePath(JSON.parse(values.FIZZYX_LOGIN_ROUTE) as string);
	return [
		{
			path: "src/lib/auth/server.ts",
			content: renderAuthTemplate(tanstackAuthServerTemplate, values),
		},
		{
			path: "src/lib/auth/session.server.ts",
			content: renderAuthTemplate(tanstackAuthSessionTemplate, values),
		},
		{
			path: "src/routes/api/auth/login.ts",
			content: renderAuthTemplate(tanstackLoginApiTemplate, values),
		},
		staticFile("src/routes/api/auth/logout.ts", tanstackLogoutApiTemplate),
		staticFile("src/routes/api/admin/$.ts", tanstackProxyTemplate),
		{
			path: `src/routes/${loginRoute}.tsx`,
			content: renderAuthTemplate(tanstackLoginTemplate, values),
		},
		{
			path: "src/routes/_admin.tsx",
			content: renderAuthTemplate(tanstackAuthLayoutTemplate, values),
		},
	];
};

export const renderAdminApp = (plan: AdminAppPlan, framework: AdminFramework): GeneratedFile[] => {
	const authEnabled = plan.auth.status === "configured";
	const apiBaseUrl = authEnabled
		? '"/api/admin"'
		: framework === "nextjs"
			? 'process.env.NEXT_PUBLIC_API_BASE_URL ?? ""'
			: 'import.meta.env.VITE_API_BASE_URL ?? ""';
	const shared = [
		renderPlan(plan),
		{
			path: ".env.example",
			content: authEnabled
				? "# Server-only upstream API URL (never expose tokens here)\nAPI_BASE_URL=https://api.example.com\n"
				: framework === "nextjs"
					? "NEXT_PUBLIC_API_BASE_URL=https://api.example.com\n"
					: "VITE_API_BASE_URL=https://api.example.com\n",
		},
		staticFile(".agents/skills/fizzyx-openapi-admin-auth/SKILL.md", adminAuthSkillTemplate),
		staticFile(
			".agents/skills/fizzyx-openapi-admin-auth/agents/openai.yaml",
			adminAuthSkillMetadataTemplate,
		),
		staticFile(
			".agents/skills/fizzyx-openapi-admin-development/SKILL.md",
			adminDevelopmentSkillTemplate,
		),
		staticFile(
			".agents/skills/fizzyx-openapi-admin-development/agents/openai.yaml",
			adminDevelopmentSkillMetadataTemplate,
		),
		authEnabled
			? {
					path: "src/components/admin/admin-shell.tsx",
					content: renderAuthTemplate(authAdminShellTemplate, authTemplateValues(plan)!),
				}
			: staticFile("src/components/admin/admin-shell.tsx", adminShellTemplate),
		staticFile("src/components/admin/data-table.tsx", dataTableTemplate),
		staticFile("src/components/admin/dynamic-form.tsx", dynamicFormTemplate),
		staticFile("src/components/admin/query-provider.tsx", queryProviderTemplate),
		{
			path: "src/lib/api/admin-api.ts",
			content: renderTemplate(adminApiTemplate, { FIZZYX_API_BASE_URL: apiBaseUrl }),
		},
	];
	if (framework === "nextjs") {
		const authFiles = renderNextAuth(plan);
		return [
			...shared,
			...(authFiles.length
				? authFiles
				: [staticFile("src/app/(admin)/layout.tsx", nextLayoutTemplate)]),
			...renderResources(plan, [
				renderNextList,
				renderNextCreate,
				renderNextDetail,
				renderNextEdit,
			]),
		];
	}
	const authFiles = renderTanstackAuth(plan);
	return [
		...shared,
		...(authFiles.length
			? authFiles
			: [staticFile("src/routes/_admin.tsx", tanstackLayoutTemplate)]),
		...renderResources(plan, [
			renderTanstackList,
			renderTanstackCreate,
			renderTanstackDetail,
			renderTanstackEdit,
		]),
	];
};
